### ISSUE TITLE
Occasional crashes: Bad file descriptor

### ISSUE THREAD

**Issue by bkrumnow** [wkeeling/selenium-wire#114]
Hey all,

I run selenium-wire in a multi-threaded environment for large-scale scans. Most of the time it works well, but occasionally crashes with the following error:

```
Exception in thread Thread-27614:
Traceback (most recent call last):
File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()

File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)

File "/home/...{project_directory}.../venv/lib/python3.6/site-packages/seleniumwire/proxy/proxy2.py", line 227, in server_read
    serverdata = server_sock.recv(4096)

File "/usr/lib/python3.6/ssl.py", line 997, in recv
    return self.read(buflen)

File "/usr/lib/python3.6/ssl.py", line 874, in read
    return self._sslobj.read(len, buffer)

File "/usr/lib/python3.6/ssl.py", line 633, in read
    v = self._sslobj.read(len)

OSError: [Errno 9] Bad file descriptor
```

I am running Ubuntu 18.04.4 LTS (bionic), selenium-wire 1.1.0 with Chrome 83. 

Thanks in advanced for your help!

**Comment by chemeng** [comment]
same issue as well

**Comment by wkeeling** [comment]
Thanks @bkrumnow @chemeng 

It looks as though a read error is happening on a websocket that Selenium Wire isn't handling properly.

I've added some better error handling and created a new version 1.1.1. Would you be able to upgrade to version 1.1.1 and see whether that resolves the issue for you?

**Comment by chemeng** [comment]
Awesome, yes that solved it!

**Comment by bkrumnow** [comment]
Sure, I will do some testing on my site as well.

**Comment by bkrumnow** [comment]
I could trace it back to hanging chrome instances, which appears to happen on Linux since Chrome 79. Meaning, your changes resolve the problem. Thanks again!
