### ISSUE TITLE
Chromium 80.0.3987.162 unexpectedly loses connection to the internet [Debian 10.4, v1.2.3]

### ISSUE THREAD

**Issue by SuperSonicHub1** [wkeeling/selenium-wire#125]
When running a script, the browser will sometimes return `ERR_EMPTY_RESPONSE` and upon attempting a reload returns `ERR_PROXY_CONNECTION_FAILED`, most likey due to Selenium closing from a time out.  The annoying thing about this bug is that I have no way of accounting for it and comes up quite randomly, thus making reproducing it quite a hassle. Do keep in mind that I am running Debian via [Crostini](https://chromium.googlesource.com/chromiumos/docs/+/master/containers_and_vms.md), although I run into no issues when browsing the internet normally.

My full script (downloads streams and subtitles from vrv.co; episodeScraper() test link: https://vrv.co/watch/GR8DD279R/Are-You-Afraid-of-the-Dark:The-Tale-of-the-Phantom-Cab , seasonScraper test link: https://vrv.co/series/GRXJ020MY/Are-You-Afraid-of-the-Dark) :
 
``` python
from seleniumwire import webdriver
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from bs4 import BeautifulSoup
from wget import download
from re import sub
import os
import requests
from sys import exit


def episodeScraper(username, password, url, path=""):

    driver = webdriver.Chrome(os.path.abspath("chromedriver"))
    wait = WebDriverWait(driver, 120)

    # Login to VRV in order to have the 'streams?' link revealed

    print("Logging in...")
    driver.get(url)
    driver.implicitly_wait(15)

    element = wait.until(
        EC.element_to_be_clickable(
            (
                By.CSS_SELECTOR,
                "#content > div > div.erc-header > div.header-content > div.header-right > ul > li:nth-child(4) > div > div.erc-header-tile",
            )
        )
    )  # Enable account dropdown
    element.click()

    element = wait.until(
        EC.element_to_be_clickable(
            (
                By.XPATH,
                "/html/body/div[1]/div/div[2]/div[1]/div[3]/ul/li[4]/div/div[3]/div/a[2]",
            )
        )
    )  # Click on sign in button
    element.click()

    element = wait.until(
        EC.element_to_be_clickable((By.CLASS_NAME, "email-input"))
    )  # Entering username
    element.send_keys(username)

    element = wait.until(
        EC.element_to_be_clickable((By.CLASS_NAME, "password-input"))
    )  # Entering password
    element.send_keys(password)

    element = wait.until(
        EC.element_to_be_clickable((By.CLASS_NAME, "signin-submit"))
    )  # Submit user info
    element.click()
    driver.implicitly_wait(15)

    # Creating a folder name format and ripping an HD thumbnail via Beautiful Soup

    print("Ripping title name and thumbnail...")

    wait.until(
        EC.presence_of_element_located(
            (
                By.CSS_SELECTOR,
                "#content > div > div.app-body-wrapper > div > div.video-content > div.content > div.media-metadata > a > img",
            )
        )
    )  # Wait for source of title to load
    wait.until(
        EC.presence_of_element_located((By.CLASS_NAME, "video-player"))
    )  # Wait for video player to load

    page_soup = BeautifulSoup(driver.page_source, "html.parser")
    folder_name = os.path.join(
        path,
        page_soup.title.string.split("Watch on VRV")[0]
        + page_soup.find_all("img", class_="c-content-image")[0]["alt"],
    )

    if not os.path.exists(folder_name):
        os.makedirs(folder_name)

    driver.switch_to.frame(
        driver.find_element_by_tag_name("iframe")
    )  # Switch to video player frame
    wait.until(EC.presence_of_element_located((By.CLASS_NAME, "vjs-poster")))
    video_soup = BeautifulSoup(driver.page_source, "html.parser")
    thumbnail_url = sub(
        r"(background-image: url\(\"|\"\);)",
        "",
        video_soup.find("div", class_="vjs-poster")["style"],
        0,
    )
    thumbnail = download(
        thumbnail_url, out=os.path.join(folder_name, "thumbnail.jpeg")
    )
    driver.switch_to.default_content()  # Return to main content
    driver.implicitly_wait(15)

    # Parse the browser requests in order to find the "?streams" link and downloading the playlist and subtitles

    print("Downloading video and subtitles...")

    request = driver.wait_for_request(
        "/cms/v2/US/M3/boomerang,cartoonhangover,crunchyroll,fandor,hidive,mondo,nicksplat,roosterteeth,tested,vrvselect/videos/",
        timeout=120,
    )
    stream_json = requests.get(request.path, headers={"User-Agent": "vrv-dl"}).json()
    driver.quit()

    if stream_json == None:
        exit("Couldln't locate the ?streams link; try, try again.")
    else:
        stream = download(
            stream_json["streams"]["adaptive_dash"][""]["url"],
            out=os.path.join(folder_name, "stream.m3u8"),
        )
        subs = download(
            stream_json["subtitles"]["en-US"]["url"],
            out=os.path.join(folder_name, "subtitles.ass"),
        )

    print(
        "\n==============================\n Stream at: {0} \nSubtitles at: {1} \nThumbnail at {2} \nConvert and embed at your leisure, although you can watch the .m3u8 file locally as long as you have an internet conncection.".format(
            stream, subs, thumbnail
        )
    )


def seasonScraper(username, password, url, path="output"):
    driver = webdriver.Chrome(os.path.abspath("chromedriver"))
    wait = WebDriverWait(driver, 20)

    driver.get(url)
    wait.until(
        EC.presence_of_all_elements_located((By.CLASS_NAME, "card-link"))
    )  # Where the episode links are located
    wait.until(EC.presence_of_element_located((By.CLASS_NAME, 'c-content-image'))) #Where the cover is located

    page_soup = BeautifulSoup(driver.page_source, "html.parser")
    folder_name = os.path.join(
        path, page_soup.find("div", class_="series-title").string
    )
    if not os.path.exists(folder_name):
        os.makedirs(folder_name)
    download(page_soup.select("#content > div > div.app-body-wrapper > div > div.content > div.series-metadata > div.erc-series-poster.series-poster > img")[0]['src'], out=os.path.join(folder_name, "cover.jpeg"))

    episodes = page_soup.find_all("a", class_="card-link")
    episode_links = []
    for item in episodes:
        episode_links.append("https://vrv.co" + item["href"])
    driver.quit()

    for item in episode_links:
        episodeScraper(username, password, item, folder_name)
```

**Comment by wkeeling** [comment]
Thanks for raising this. Have you tried increasing the connection timeout to cater for slower responses? e.g. 

```
options = {
    'connection_timeout': 20
}
driver = webdriver.Chrome(os.path.abspath("chromedriver"), seleniumwire_options=options)
```

**Comment by SuperSonicHub1** [comment]
Adding the option had no effect.
![image](https://user-images.githubusercontent.com/25624882/85328174-44c7d200-b49e-11ea-8adb-418ecef1c7ec.png)

**Comment by Dassy23** [comment]
Having similar issue

**Comment by wkeeling** [comment]
@SuperSonicHub1 could you enable logging at the top of your script? If an error is causing the empty response you're seeing, we should see a traceback once logging is enabled. i.e.

```
import logging
logging.basicConfig(level=logging.DEBUG)
```

**Comment by SuperSonicHub1** [comment]
Here's what I got:
```
INFO:seleniumwire.proxy.client:Created proxy listening on 127.0.0.1:42419
DEBUG:selenium.webdriver.remote.remote_connection:POST http://127.0.0.1:55053/session {"capabilities": {"firstMatch": [{}], "alwaysMatch": {"browserName": "chrome", "platformName": "any", "proxy": {"proxyType": "manual", "httpProxy": "127.0.0.1:42419", "sslProxy": "127.0.0.1:42419", "noProxy": ""}, "acceptInsecureCerts": true}}, "desiredCapabilities": {"browserName": "chrome", "version": "", "platform": "ANY", "proxy": {"proxyType": "manual", "httpProxy": "127.0.0.1:42419", "sslProxy": "127.0.0.1:42419", "noProxy": ""}, "acceptInsecureCerts": true}}
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 127.0.0.1:55053
DEBUG:seleniumwire.proxy.handler:accounts.google.com:443 200
INFO:seleniumwire.proxy.handler:Capturing request: https://accounts.google.com/ListAccounts?gpsia=1&source=ChromiumBrowser&json=standard
INFO:seleniumwire.proxy.handler:Capturing response: https://accounts.google.com/ListAccounts?gpsia=1&source=ChromiumBrowser&json=standard 200 OK
DEBUG:seleniumwire.proxy.handler:https://accounts.google.com/ListAccounts?gpsia=1&source=ChromiumBrowser&json=standard 200
DEBUG:urllib3.connectionpool:http://127.0.0.1:55053 "POST /session HTTP/1.1" 200 734
DEBUG:selenium.webdriver.remote.remote_connection:Finished Request
DEBUG:selenium.webdriver.remote.remote_connection:POST http://127.0.0.1:55053/session/9c12bd052617c62ef6a8fd26e03eb382/url {"url": "https://vrv.co/series/GYQ4MW246/Naruto-Shippuden, "}
DEBUG:seleniumwire.proxy.handler:vrv.co:443 200
DEBUG:seleniumwire.proxy.handler:vrv.co:443 200
INFO:seleniumwire.proxy.handler:Capturing request: https://vrv.co/series/GYQ4MW246/Naruto-Shippuden,
ERROR:seleniumwire.proxy.handler:Error making request
Traceback (most recent call last):
  File "/home/kyleanthonywilliams2/vrv-dl/vrv_dl_env/lib/python3.7/site-packages/seleniumwire/proxy/proxy2.py", line 91, in proxy_request
    res = conn.getresponse()
  File "/usr/lib/python3.7/http/client.py", line 1336, in getresponse
    response.begin()
  File "/usr/lib/python3.7/http/client.py", line 306, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.7/http/client.py", line 267, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.7/ssl.py", line 1052, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.7/ssl.py", line 911, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out
DEBUG:urllib3.connectionpool:http://127.0.0.1:55053 "POST /session/9c12bd052617c62ef6a8fd26e03eb382/url HTTP/1.1" 200 14
DEBUG:selenium.webdriver.remote.remote_connection:Finished Request
DEBUG:selenium.webdriver.remote.remote_connection:POST http://127.0.0.1:55053/session/9c12bd052617c62ef6a8fd26e03eb382/elements {"using": "css selector", "value": ".card-link"}
DEBUG:urllib3.connectionpool:http://127.0.0.1:55053 "POST /session/9c12bd052617c62ef6a8fd26e03eb382/elements HTTP/1.1" 200 12
DEBUG:selenium.webdriver.remote.remote_connection:Finished Request
DEBUG:seleniumwire.proxy.handler:www.gstatic.com:443 200
INFO:seleniumwire.proxy.handler:Capturing request: https://www.gstatic.com/chrome/intelligence/assist/ranker/models/translate/2017/03/translate_ranker_model_20170329.pb.bin
DEBUG:selenium.webdriver.remote.remote_connection:POST http://127.0.0.1:55053/session/9c12bd052617c62ef6a8fd26e03eb382/elements {"using": "css selector", "value": ".card-link"}
DEBUG:urllib3.connectionpool:http://127.0.0.1:55053 "POST /session/9c12bd052617c62ef6a8fd26e03eb382/elements HTTP/1.1" 200 12
DEBUG:selenium.webdriver.remote.remote_connection:Finished Request
INFO:seleniumwire.proxy.handler:Capturing response: https://www.gstatic.com/chrome/intelligence/assist/ranker/models/translate/2017/03/translate_ranker_model_20170329.pb.bin 200 OK
DEBUG:seleniumwire.proxy.handler:https://www.gstatic.com/chrome/intelligence/assist/ranker/models/translate/2017/03/translate_ranker_model_20170329.pb.bin 200
DEBUG:selenium.webdriver.remote.remote_connection:POST http://127.0.0.1:55053/session/9c12bd052617c62ef6a8fd26e03eb382/elements {"using": "css selector", "value": ".card-link"}
DEBUG:urllib3.connectionpool:http://127.0.0.1:55053 "POST /session/9c12bd052617c62ef6a8fd26e03eb382/elements HTTP/1.1" 200 12
DEBUG:selenium.webdriver.remote.remote_connection:Finished Request
DEBUG:selenium.webdriver.remote.remote_connection:POST http://127.0.0.1:55053/session/9c12bd052617c62ef6a8fd26e03eb382/elements {"using": "css selector", "value": ".card-link"}
DEBUG:urllib3.connectionpool:http://127.0.0.1:55053 "POST /session/9c12bd052617c62ef6a8fd26e03eb382/elements HTTP/1.1" 200 12
DEBUG:selenium.webdriver.remote.remote_connection:Finished Request
DEBUG:selenium.webdriver.remote.remote_connection:POST http://127.0.0.1:55053/session/9c12bd052617c62ef6a8fd26e03eb382/elements {"using": "css selector", "value": ".card-link"}
DEBUG:urllib3.connectionpool:http://127.0.0.1:55053 "POST /session/9c12bd052617c62ef6a8fd26e03eb382/elements HTTP/1.1" 200 12
DEBUG:selenium.webdriver.remote.remote_connection:Finished Request
DEBUG:selenium.webdriver.remote.remote_connection:POST http://127.0.0.1:55053/session/9c12bd052617c62ef6a8fd26e03eb382/elements {"using": "css selector", "value": ".card-link"}
DEBUG:urllib3.connectionpool:http://127.0.0.1:55053 "POST /session/9c12bd052617c62ef6a8fd26e03eb382/elements HTTP/1.1" 200 12
DEBUG:selenium.webdriver.remote.remote_connection:Finished Request
DEBUG:selenium.webdriver.remote.remote_connection:POST http://127.0.0.1:55053/session/9c12bd052617c62ef6a8fd26e03eb382/elements {"using": "css selector", "value": ".card-link"}
DEBUG:urllib3.connectionpool:http://127.0.0.1:55053 "POST /session/9c12bd052617c62ef6a8fd26e03eb382/elements HTTP/1.1" 200 12
DEBUG:selenium.webdriver.remote.remote_connection:Finished Request
DEBUG:selenium.webdriver.remote.remote_connection:POST http://127.0.0.1:55053/session/9c12bd052617c62ef6a8fd26e03eb382/elements {"using": "css selector", "value": ".card-link"}
DEBUG:urllib3.connectionpool:http://127.0.0.1:55053 "POST /session/9c12bd052617c62ef6a8fd26e03eb382/elements HTTP/1.1" 200 12
DEBUG:selenium.webdriver.remote.remote_connection:Finished Request
DEBUG:selenium.webdriver.remote.remote_connection:POST http://127.0.0.1:55053/session/9c12bd052617c62ef6a8fd26e03eb382/elements {"using": "css selector", "value": ".card-link"}
DEBUG:urllib3.connectionpool:http://127.0.0.1:55053 "POST /session/9c12bd052617c62ef6a8fd26e03eb382/elements HTTP/1.1" 200 12
DEBUG:selenium.webdriver.remote.remote_connection:Finished Request
DEBUG:selenium.webdriver.remote.remote_connection:POST http://127.0.0.1:55053/session/9c12bd052617c62ef6a8fd26e03eb382/elements {"using": "css selector", "value": ".card-link"}
DEBUG:urllib3.connectionpool:http://127.0.0.1:55053 "POST /session/9c12bd052617c62ef6a8fd26e03eb382/elements HTTP/1.1" 200 12
DEBUG:selenium.webdriver.remote.remote_connection:Finished Request
DEBUG:selenium.webdriver.remote.remote_connection:POST http://127.0.0.1:55053/session/9c12bd052617c62ef6a8fd26e03eb382/elements {"using": "css selector", "value": ".card-link"}
DEBUG:urllib3.connectionpool:http://127.0.0.1:55053 "POST /session/9c12bd052617c62ef6a8fd26e03eb382/elements HTTP/1.1" 200 12
DEBUG:selenium.webdriver.remote.remote_connection:Finished Request
DEBUG:selenium.webdriver.remote.remote_connection:POST http://127.0.0.1:55053/session/9c12bd052617c62ef6a8fd26e03eb382/elements {"using": "css selector", "value": ".card-link"}
DEBUG:urllib3.connectionpool:http://127.0.0.1:55053 "POST /session/9c12bd052617c62ef6a8fd26e03eb382/elements HTTP/1.1" 200 12
DEBUG:selenium.webdriver.remote.remote_connection:Finished Request
DEBUG:selenium.webdriver.remote.remote_connection:POST http://127.0.0.1:55053/session/9c12bd052617c62ef6a8fd26e03eb382/elements {"using": "css selector", "value": ".card-link"}
DEBUG:urllib3.connectionpool:http://127.0.0.1:55053 "POST /session/9c12bd052617c62ef6a8fd26e03eb382/elements HTTP/1.1" 200 12
DEBUG:selenium.webdriver.remote.remote_connection:Finished Request
DEBUG:selenium.webdriver.remote.remote_connection:POST http://127.0.0.1:55053/session/9c12bd052617c62ef6a8fd26e03eb382/elements {"using": "css selector", "value": ".card-link"}
DEBUG:urllib3.connectionpool:http://127.0.0.1:55053 "POST /session/9c12bd052617c62ef6a8fd26e03eb382/elements HTTP/1.1" 200 12
DEBUG:selenium.webdriver.remote.remote_connection:Finished Request
DEBUG:selenium.webdriver.remote.remote_connection:POST http://127.0.0.1:55053/session/9c12bd052617c62ef6a8fd26e03eb382/elements {"using": "css selector", "value": ".card-link"}
DEBUG:urllib3.connectionpool:http://127.0.0.1:55053 "POST /session/9c12bd052617c62ef6a8fd26e03eb382/elements HTTP/1.1" 200 12
DEBUG:selenium.webdriver.remote.remote_connection:Finished Request
DEBUG:selenium.webdriver.remote.remote_connection:POST http://127.0.0.1:55053/session/9c12bd052617c62ef6a8fd26e03eb382/elements {"using": "css selector", "value": ".card-link"}
DEBUG:urllib3.connectionpool:http://127.0.0.1:55053 "POST /session/9c12bd052617c62ef6a8fd26e03eb382/elements HTTP/1.1" 200 12
DEBUG:selenium.webdriver.remote.remote_connection:Finished Request
DEBUG:selenium.webdriver.remote.remote_connection:POST http://127.0.0.1:55053/session/9c12bd052617c62ef6a8fd26e03eb382/elements {"using": "css selector", "value": ".card-link"}
DEBUG:urllib3.connectionpool:http://127.0.0.1:55053 "POST /session/9c12bd052617c62ef6a8fd26e03eb382/elements HTTP/1.1" 200 12
DEBUG:selenium.webdriver.remote.remote_connection:Finished Request
DEBUG:selenium.webdriver.remote.remote_connection:POST http://127.0.0.1:55053/session/9c12bd052617c62ef6a8fd26e03eb382/elements {"using": "css selector", "value": ".card-link"}
DEBUG:urllib3.connectionpool:http://127.0.0.1:55053 "POST /session/9c12bd052617c62ef6a8fd26e03eb382/elements HTTP/1.1" 200 12
DEBUG:selenium.webdriver.remote.remote_connection:Finished Request
DEBUG:selenium.webdriver.remote.remote_connection:POST http://127.0.0.1:55053/session/9c12bd052617c62ef6a8fd26e03eb382/elements {"using": "css selector", "value": ".card-link"}
DEBUG:urllib3.connectionpool:http://127.0.0.1:55053 "POST /session/9c12bd052617c62ef6a8fd26e03eb382/elements HTTP/1.1" 200 12
DEBUG:selenium.webdriver.remote.remote_connection:Finished Request
DEBUG:selenium.webdriver.remote.remote_connection:POST http://127.0.0.1:55053/session/9c12bd052617c62ef6a8fd26e03eb382/elements {"using": "css selector", "value": ".card-link"}
DEBUG:urllib3.connectionpool:http://127.0.0.1:55053 "POST /session/9c12bd052617c62ef6a8fd26e03eb382/elements HTTP/1.1" 200 12
DEBUG:selenium.webdriver.remote.remote_connection:Finished Request
DEBUG:selenium.webdriver.remote.remote_connection:POST http://127.0.0.1:55053/session/9c12bd052617c62ef6a8fd26e03eb382/elements {"using": "css selector", "value": ".card-link"}
DEBUG:urllib3.connectionpool:http://127.0.0.1:55053 "POST /session/9c12bd052617c62ef6a8fd26e03eb382/elements HTTP/1.1" 200 12
DEBUG:selenium.webdriver.remote.remote_connection:Finished Request
DEBUG:selenium.webdriver.remote.remote_connection:POST http://127.0.0.1:55053/session/9c12bd052617c62ef6a8fd26e03eb382/elements {"using": "css selector", "value": ".card-link"}
DEBUG:urllib3.connectionpool:http://127.0.0.1:55053 "POST /session/9c12bd052617c62ef6a8fd26e03eb382/elements HTTP/1.1" 200 12
DEBUG:selenium.webdriver.remote.remote_connection:Finished Request
DEBUG:selenium.webdriver.remote.remote_connection:POST http://127.0.0.1:55053/session/9c12bd052617c62ef6a8fd26e03eb382/elements {"using": "css selector", "value": ".card-link"}
DEBUG:urllib3.connectionpool:http://127.0.0.1:55053 "POST /session/9c12bd052617c62ef6a8fd26e03eb382/elements HTTP/1.1" 200 12
DEBUG:selenium.webdriver.remote.remote_connection:Finished Request
DEBUG:selenium.webdriver.remote.remote_connection:POST http://127.0.0.1:55053/session/9c12bd052617c62ef6a8fd26e03eb382/elements {"using": "css selector", "value": ".card-link"}
DEBUG:urllib3.connectionpool:http://127.0.0.1:55053 "POST /session/9c12bd052617c62ef6a8fd26e03eb382/elements HTTP/1.1" 200 12
DEBUG:selenium.webdriver.remote.remote_connection:Finished Request
DEBUG:selenium.webdriver.remote.remote_connection:POST http://127.0.0.1:55053/session/9c12bd052617c62ef6a8fd26e03eb382/elements {"using": "css selector", "value": ".card-link"}
DEBUG:urllib3.connectionpool:http://127.0.0.1:55053 "POST /session/9c12bd052617c62ef6a8fd26e03eb382/elements HTTP/1.1" 200 12
DEBUG:selenium.webdriver.remote.remote_connection:Finished Request
DEBUG:selenium.webdriver.remote.remote_connection:POST http://127.0.0.1:55053/session/9c12bd052617c62ef6a8fd26e03eb382/elements {"using": "css selector", "value": ".card-link"}
DEBUG:urllib3.connectionpool:http://127.0.0.1:55053 "POST /session/9c12bd052617c62ef6a8fd26e03eb382/elements HTTP/1.1" 200 12
DEBUG:selenium.webdriver.remote.remote_connection:Finished Request
DEBUG:selenium.webdriver.remote.remote_connection:POST http://127.0.0.1:55053/session/9c12bd052617c62ef6a8fd26e03eb382/elements {"using": "css selector", "value": ".card-link"}
DEBUG:urllib3.connectionpool:http://127.0.0.1:55053 "POST /session/9c12bd052617c62ef6a8fd26e03eb382/elements HTTP/1.1" 200 12
DEBUG:selenium.webdriver.remote.remote_connection:Finished Request
DEBUG:selenium.webdriver.remote.remote_connection:POST http://127.0.0.1:55053/session/9c12bd052617c62ef6a8fd26e03eb382/elements {"using": "css selector", "value": ".card-link"}
DEBUG:urllib3.connectionpool:http://127.0.0.1:55053 "POST /session/9c12bd052617c62ef6a8fd26e03eb382/elements HTTP/1.1" 200 12
DEBUG:selenium.webdriver.remote.remote_connection:Finished Request
DEBUG:selenium.webdriver.remote.remote_connection:POST http://127.0.0.1:55053/session/9c12bd052617c62ef6a8fd26e03eb382/elements {"using": "css selector", "value": ".card-link"}
DEBUG:urllib3.connectionpool:http://127.0.0.1:55053 "POST /session/9c12bd052617c62ef6a8fd26e03eb382/elements HTTP/1.1" 200 12
DEBUG:selenium.webdriver.remote.remote_connection:Finished Request
DEBUG:selenium.webdriver.remote.remote_connection:POST http://127.0.0.1:55053/session/9c12bd052617c62ef6a8fd26e03eb382/elements {"using": "css selector", "value": ".card-link"}
DEBUG:urllib3.connectionpool:http://127.0.0.1:55053 "POST /session/9c12bd052617c62ef6a8fd26e03eb382/elements HTTP/1.1" 200 12
DEBUG:selenium.webdriver.remote.remote_connection:Finished Request
DEBUG:selenium.webdriver.remote.remote_connection:POST http://127.0.0.1:55053/session/9c12bd052617c62ef6a8fd26e03eb382/elements {"using": "css selector", "value": ".card-link"}
DEBUG:urllib3.connectionpool:http://127.0.0.1:55053 "POST /session/9c12bd052617c62ef6a8fd26e03eb382/elements HTTP/1.1" 200 12
DEBUG:selenium.webdriver.remote.remote_connection:Finished Request
DEBUG:selenium.webdriver.remote.remote_connection:POST http://127.0.0.1:55053/session/9c12bd052617c62ef6a8fd26e03eb382/elements {"using": "css selector", "value": ".card-link"}
DEBUG:urllib3.connectionpool:http://127.0.0.1:55053 "POST /session/9c12bd052617c62ef6a8fd26e03eb382/elements HTTP/1.1" 200 12
DEBUG:selenium.webdriver.remote.remote_connection:Finished Request
DEBUG:selenium.webdriver.remote.remote_connection:POST http://127.0.0.1:55053/session/9c12bd052617c62ef6a8fd26e03eb382/elements {"using": "css selector", "value": ".card-link"}
DEBUG:urllib3.connectionpool:http://127.0.0.1:55053 "POST /session/9c12bd052617c62ef6a8fd26e03eb382/elements HTTP/1.1" 200 12
DEBUG:selenium.webdriver.remote.remote_connection:Finished Request
DEBUG:selenium.webdriver.remote.remote_connection:POST http://127.0.0.1:55053/session/9c12bd052617c62ef6a8fd26e03eb382/elements {"using": "css selector", "value": ".card-link"}
DEBUG:urllib3.connectionpool:http://127.0.0.1:55053 "POST /session/9c12bd052617c62ef6a8fd26e03eb382/elements HTTP/1.1" 200 12
DEBUG:selenium.webdriver.remote.remote_connection:Finished Request
DEBUG:selenium.webdriver.remote.remote_connection:POST http://127.0.0.1:55053/session/9c12bd052617c62ef6a8fd26e03eb382/elements {"using": "css selector", "value": ".card-link"}
DEBUG:urllib3.connectionpool:http://127.0.0.1:55053 "POST /session/9c12bd052617c62ef6a8fd26e03eb382/elements HTTP/1.1" 200 12
DEBUG:selenium.webdriver.remote.remote_connection:Finished Request
DEBUG:selenium.webdriver.remote.remote_connection:POST http://127.0.0.1:55053/session/9c12bd052617c62ef6a8fd26e03eb382/elements {"using": "css selector", "value": ".card-link"}
DEBUG:urllib3.connectionpool:http://127.0.0.1:55053 "POST /session/9c12bd052617c62ef6a8fd26e03eb382/elements HTTP/1.1" 200 12
DEBUG:selenium.webdriver.remote.remote_connection:Finished Request
Traceback (most recent call last):
  File "/home/kyleanthonywilliams2/vrv-dl/main.py", line 185, in <module>
    "https://vrv.co/series/GYQ4MW246/Naruto-Shippuden, ",
  File "/home/kyleanthonywilliams2/vrv-dl/main.py", line 153, in seasonScraper
    EC.presence_of_all_elements_located((By.CLASS_NAME, "card-link"))
  File "/home/kyleanthonywilliams2/vrv-dl/vrv_dl_env/lib/python3.7/site-packages/selenium/webdriver/support/wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
```

**Comment by idxn** [comment]
@SuperSonicHub1 Have you resolved your issue? It would be great if you can share what you have done.

**Comment by SuperSonicHub1** [comment]
I haven't. I simply moved to web scraping, which kinda worked, and then
attempted to get the website's OAuth API working in my favor, which failed
terribly. Ultimately, youtube-dl already does what I was trying to do, just
with much less flexibility, so I ultimately gave up. If selenium-wire
becomes more stable, I will happily return to this project. Until then, I'm
leaving this issue closed.

Kyle Williams

**Comment by wkeeling** [comment]
@SuperSonicHub1 there's a new version of Selenium Wire available (v2.0.0) which _may_ fix this. The new version introduces [backends](https://github.com/wkeeling/selenium-wire#backends) which allow you to switch to using mitmproxy as a backend. mitmproxy can better handle slow connections and busy upstream servers and in my own testing seems to improve performance generally over the default backend.

You can switch to using the mitmproxy backend by specifying it in the Selenium Wire options:

```
options = {
    'backend': 'mitmproxy',
    'mitmproxy_log_level': 'INFO'
}
driver = webdriver.Chrome(
    os.path.abspath("chromedriver"), 
    seleniumwire_options=options
)
```

You'll also need to ensure that you've installed the mitmproxy package:

```
pip install mitmproxy
```
If you decide to give it a try, let me know if you hit any issues. It's a new feature and any issues that come up I'll aim to resolve ASAP.

**Comment by SuperSonicHub1** [comment]
I'll get around to testing it.

**Comment by P-Leo10** [comment]
Can you resolved your issue? I have a similar problem and i use the new version of Selenium Wire

**Comment by SuperSonicHub1** [comment]
I tried mitmproxy and actually had worse performance than I did previously,
at least from what I can perceive, so no, I haven't resolved my issue.

Kyle Williams
