### ISSUE TITLE
I don't want to use a proxy, but it keeps getting an error

### ISSUE THREAD

**Issue by thuyetbn** [wkeeling/selenium-wire#130]
Error making request
Traceback (most recent call last):
  File "C:\Users\BinDz\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\seleniumwire\proxy\proxy2.py", line 90, in proxy_request
    conn.request(self.command, path, req_body, dict(req.headers))
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1008.0_x64__qbz5n2kfra8p0\lib\http\client.py", line 1240, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1008.0_x64__qbz5n2kfra8p0\lib\http\client.py", line 1286, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1008.0_x64__qbz5n2kfra8p0\lib\http\client.py", line 1235, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1008.0_x64__qbz5n2kfra8p0\lib\http\client.py", line 1006, in _send_output
    self.send(msg)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1008.0_x64__qbz5n2kfra8p0\lib\http\client.py", line 946, in send
    self.connect()
  File "C:\Users\BinDz\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\seleniumwire\proxy\proxy2.py", line 367, in connect
    super().connect()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1008.0_x64__qbz5n2kfra8p0\lib\http\client.py", line 1402, in connect
    super().connect()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1008.0_x64__qbz5n2kfra8p0\lib\http\client.py", line 917, in connect
    self.sock = self._create_connection(
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1008.0_x64__qbz5n2kfra8p0\lib\socket.py", line 787, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1008.0_x64__qbz5n2kfra8p0\lib\socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed
Error making request
Traceback (most recent call last):
  File "C:\Users\BinDz\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\seleniumwire\proxy\proxy2.py", line 90, in proxy_request
    conn.request(self.command, path, req_body, dict(req.headers))
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1008.0_x64__qbz5n2kfra8p0\lib\http\client.py", line 1240, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1008.0_x64__qbz5n2kfra8p0\lib\http\client.py", line 1286, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1008.0_x64__qbz5n2kfra8p0\lib\http\client.py", line 1235, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1008.0_x64__qbz5n2kfra8p0\lib\http\client.py", line 1006, in _send_output
    self.send(msg)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1008.0_x64__qbz5n2kfra8p0\lib\http\client.py", line 946, in send
    self.connect()
  File "C:\Users\BinDz\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\seleniumwire\proxy\proxy2.py", line 367, in connect
    super().connect()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1008.0_x64__qbz5n2kfra8p0\lib\http\client.py", line 1402, in connect
    super().connect()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1008.0_x64__qbz5n2kfra8p0\lib\http\client.py", line 917, in connect
    self.sock = self._create_connection(
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1008.0_x64__qbz5n2kfra8p0\lib\socket.py", line 787, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1008.0_x64__qbz5n2kfra8p0\lib\socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed

**Comment by wkeeling** [comment]
Could you post the selenium wire options you're using to create the webdriver?

**Comment by wkeeling** [comment]
I suspect the issue is that the proxy configuration has not be specified correctly in the Selenium Wire options, as the traceback above indicates that Selenium Wire has failed to connect to the proxy host. The correct proxy configuration format should be:

```
options = {
    'proxy': {
        'http': 'http://user:pass@192.168.10.100:8888',
        'https': 'https://user:pass@192.168.10.100:8889',
        'no_proxy': 'localhost,127.0.0.1'
    }
}
driver = webdriver.Firefox(seleniumwire_options=options)
```

**Comment by Dfte** [comment]
Hi, 

I'm reopening this one because i came across the same bug and went crazy for like 3 hours.
If you try to screenshot a vhost for which there is no A record, the driver will spit a huge stack trace:

![image](https://user-images.githubusercontent.com/23189983/101688938-0387a680-3a6d-11eb-9130-9050ea16ee2e.png)

So what is strange is that the proxy2.py is called even tho i'm not specifying any proxy. Below you'll find the code i used to trigger the bug (which is basically the code you provide in the documentation):

```
from seleniumwire import webdriver  # Import from seleniumwire
 # Create a new instance of the Firefox driver
 driver = webdriver.Firefox()
 
 # Go to the Google home page
 driver.get("http:/something.that.doesntexist.com/")
 
 # Access requests via the `requests` attribute
 for request in driver.requests:
     if request.response:
         print(
             request.url,
             request.response.status_code,
         )
```

Note that even if you driver.get() a valid domain and the vhost is loading some data from another domain which is not pointing to an IP, you will get the error. This error is more related to the http.client library i guess but may be you'll figure something out. May be just tell seleniumwire to not print the errors ?

Great library tho, thanks for your work dude :)

**Comment by Dfte** [comment]
I guess a simple workaround would be to try to resolve each domains before trying to load the resources from them. Altought that would mean that both the seleniumwire and the http.client library would launch the same DNS query.
