### ISSUE TITLE
Key error Content-Length

### ISSUE THREAD

**Issue by kpchand** [wkeeling/selenium-wire#132]
For this code:

```
from seleniumwire import webdriver  # Import from seleniumwire

# Create a new instance of the Firefox driver
driver = webdriver.Firefox()

# Go to the Google home page
driver.get('https://www.mycompany.com/')

# Access requests via the `requests` attribute
for request in driver.requests:
    if request.response:
        print(
            request.path,
            request.response.status_code,
            request.response.headers['Content-Type']
        )
```

It first logs several requests, but then fails followingly:

> Traceback (most recent call last):
>   File ".\test.py", line 15, in <module>
>     request.response.headers['Content-Type']
>   File "D:\envs\cbot-GvGARpUM\lib\site-packages\seleniumwire\webdriver\request.py", line 293, in __getitem__
>     return self._store[key.lower()][1]
> KeyError: 'content-type'
> PS D:\main\gdrive\core\cbot\dmxbot>

**Comment by wkeeling** [comment]
It seems as though there's a response that's missing a `Content-Type` header. You could use a default if the header doesn't exist:

```
for request in driver.requests:
    if request.response:
        print(
            request.path,
            request.response.status_code,
            request.response.headers.get('Content-Type', '<no content type>')
        )
```

or alternatively test for it:

```
for request in driver.requests:
    if request.response and 'Content-Type' in request.response.headers:
        print(
            request.path,
            request.response.status_code,
            request.response.headers['Content-Type']
        )
```

**Comment by kpchand** [comment]
That worked. Thanks.
