### ISSUE TITLE
socket.timeout: timed out

### ISSUE THREAD

**Issue by Dd-ouni** [wkeeling/selenium-wire#146]
`
seleniumwire.proxy.handler:handler.py:401 Error making request
Traceback (most recent call last):
  File "c:\users\ak\desktop\pytest_po_web\venv\lib\site-packages\seleniumwire\proxy\proxy2.py", line 91, in proxy_request
    conn.request(self.command, path, req_body, dict(req.headers))
  File "D:\Python\Python38\lib\http\client.py", line 1255, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "D:\Python\Python38\lib\http\client.py", line 1301, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "D:\Python\Python38\lib\http\client.py", line 1250, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "D:\Python\Python38\lib\http\client.py", line 1010, in _send_output
    self.send(msg)
  File "D:\Python\Python38\lib\http\client.py", line 950, in send
    self.connect()
  File "c:\users\ak\desktop\pytest_po_web\venv\lib\site-packages\seleniumwire\proxy\proxy2.py", line 368, in connect
    super().connect()
  File "D:\Python\Python38\lib\http\client.py", line 1417, in connect
    super().connect()
  File "D:\Python\Python38\lib\http\client.py", line 921, in connect
    self.sock = self._create_connection(
  File "D:\Python\Python38\lib\socket.py", line 808, in create_connection
    raise err
  File "D:\Python\Python38\lib\socket.py", line 796, in create_connection
    sock.connect(sa)
socket.timeout: timed out
`

Thank you author, and sorry for my limited level. Can not find the answer from the error.

**Comment by INFINITEY6622** [comment]
after driver.get you have to wait for your request
https://github.com/wkeeling/selenium-wire#waiting-for-a-request
### example:
***
driver.get('https://github.com/wkeeling/selenium-wire#waiting-for-a-request')
wait_for_request = driver.wait_for_request('/wkeeling/selenium-wire#waiting-for-a-request',timeout=120)
***

**Comment by Imran109** [comment]
I am facing the same issue
That too only from today

**Comment by wkeeling** [comment]
@Dd-ouni thanks for the issue. Could you post your code including any options you're passing to the webdriver instance. Plus could you let me know what version of Selenium Wire you're using?

**Comment by wkeeling** [comment]
@Dd-ouni try increasing the default timeout:

```
options = {
    'connection_timeout': 60
}
driver = webdriver.Chrome(seleniumwire_options=options)
```

**Comment by dfurmanov** [comment]
Same here
```
Error making request
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/seleniumwire/proxy/proxy2.py", line 85, in proxy_request
    conn.request(self.command, path, req_body, dict(req.headers))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1252, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1298, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1247, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 966, in send
    self.connect()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/seleniumwire/proxy/proxy2.py", line 364, in connect
    super().connect()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1414, in connect
    super().connect()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 938, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/socket.py", line 728, in create_connection
    raise err
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/socket.py", line 716, in create_connection
    sock.connect(sa)
socket.timeout: timed out
```

**Comment by wkeeling** [comment]
The core of Selenium Wire has recently been updated to improve connection handling with upstream proxies. Can you get the latest version and see whether that resolves this problem?
