### ISSUE TITLE
socket.gaierror: [Errno 11004] getaddrinfo failed

### ISSUE THREAD

**Issue by paco020295** [wkeeling/selenium-wire#148]
Hello.

I am using only this piece of code:
```
from seleniumwire import webdriver

driver = webdriver.Chrome()
base_url = "https://www.marinetraffic.com/en/users/login"
driver.get(base_url)
```

And i am getting 
```
Error making request
Traceback (most recent call last):
  File "C:\Users\Paco_\PycharmProjects\UpWorkProjects\venv\lib\site-packages\seleniumwire\proxy\proxy2.py", line 91, in proxy_request
    conn.request(self.command, path, req_body, dict(req.headers))
  File "C:\Users\Paco_\AppData\Local\Programs\Python\Python38\lib\http\client.py", line 1230, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Users\Paco_\AppData\Local\Programs\Python\Python38\lib\http\client.py", line 1276, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Users\Paco_\AppData\Local\Programs\Python\Python38\lib\http\client.py", line 1225, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Users\Paco_\AppData\Local\Programs\Python\Python38\lib\http\client.py", line 1004, in _send_output
    self.send(msg)
  File "C:\Users\Paco_\AppData\Local\Programs\Python\Python38\lib\http\client.py", line 944, in send
    self.connect()
  File "C:\Users\Paco_\PycharmProjects\UpWorkProjects\venv\lib\site-packages\seleniumwire\proxy\proxy2.py", line 368, in connect
    super().connect()
  File "C:\Users\Paco_\AppData\Local\Programs\Python\Python38\lib\http\client.py", line 1392, in connect
    super().connect()
  File "C:\Users\Paco_\AppData\Local\Programs\Python\Python38\lib\http\client.py", line 915, in connect
    self.sock = self._create_connection(
  File "C:\Users\Paco_\AppData\Local\Programs\Python\Python38\lib\socket.py", line 787, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "C:\Users\Paco_\AppData\Local\Programs\Python\Python38\lib\socket.py", line 914, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11004] getaddrinfo failed
```

This error gets printed many times, but the code continues executing (it gets stuck in driver.get()). And after 10 seconds, the website actually loads and the execution continues.

**Comment by wkeeling** [comment]
Thanks for the issue. The `gaierror` indicates that an address for a particular request has failed to resolve. The fact that the website eventually loads indicates that the error is probably occurring for requests for some non-essential resource  - e.g. some embedded Javascript, css or image etc.

I've just ran the same code locally for `https://www.marinetraffic.com/en/users/login` and I don't see any errors. Perhaps the address resolution is a local issue with your DNS server? You could try switching to an alternative DNS server to see whether that resolves. This article describes how to do that on Windows: https://www.windowscentral.com/how-change-your-pcs-dns-settings-windows-10

**Comment by paco020295** [comment]
Thanks for the response. I understand now.

Do you know how can i avoid showing those messages? Because i am getting the information i want, so i don't care about those failed requests. 

How can i catch that exception so it is not  displayed? Any help would be appreciated

**Comment by wkeeling** [comment]
You can turn down the logging to FATAL for just the package that is generating the error:

```
import logging

logging.getLogger('seleniumwire.proxy').setLevel(logging.FATAL)
```

**Comment by wkeeling** [comment]
The exception messages occur inside Selenium Wire's embedded proxy server which runs in a separate thread to the thread that runs the Selenium test code. That means it's not possible to catch the exception in the test code itself. Turning down the logging for the particular package in question is the only real way to silence the messages. 

One alternative to prevent the exception from happening to start with, would be to add the names that fail to resolve to the local [`hosts` file](https://www.onmsft.com/how-to/how-to-modify-your-hosts-file-in-windows-10-and-why-you-might-want-to) in Windows.
