### ISSUE TITLE
http.client.RemoteDisconnected: Remote end closed connection without response

### ISSUE THREAD

**Issue by aislaks** [wkeeling/selenium-wire#161]
```
Error making request
Traceback (most recent call last):
  File "C:\Users\apai\seleniumtest\.venv\lib\site-packages\seleniumwire\proxy\proxy2.py", line 92, in proxy_request
    res = conn.getresponse()
  File "C:\Python36\lib\http\client.py", line 1331, in getresponse
    response.begin()
  File "C:\Python36\lib\http\client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "C:\Python36\lib\http\client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response
```

I do not understand why this is happening and any help is appreciated

**Comment by wkeeling** [comment]
Can you post the code that creates the webdriver and makes the request?

**Comment by aislaks** [comment]
```
seleniumwire_options = {
        'proxy': {
            'http': f'http://'+proxy, 
            'https': f'https://'+proxy,
        },
        'disable_encoding': True ,
        'connection_timeout':10*60,  #sec,
        'suppress_connection_errors': True,
        'ignore_http_methods': ['POST', 'OPTIONS']
        }


        capabilities = webdriver.DesiredCapabilities.FIREFOX
        capabilities['marionette'] = True
        # capabilities.update({'acceptInsecureCerts': True, 'acceptSslCerts': True})
        fp = FirefoxProfile()
        # fp.accept_untrusted_certs = True
        
        pos = randint(0,len(user_agent_list)-1)
        write_to_file(user_agent_list[pos]+ "\n")
        fp.set_preference("general.useragent.override", user_agent_list[pos])
        fp.set_preference("dom.webdriver.enabled", False)
        fp.set_preference('useAutomationExtension', False)
        fp.set_preference("excludeSwitches", "enable-automation")
        fp.set_preference("dom.webnotifications.enabled", False)
        fp.set_preference("geo.enabled", False)
        fp.set_preference("geo.prompt.testing", False)
        fp.set_preference("geo.prompt.testing.allow", False)
        fp.set_preference("permissions.default.image", 2)
        fp.update_preferences()
        browser = webdriver.Firefox(firefox_profile = fp,seleniumwire_options=seleniumwire_options)
```

**Comment by wkeeling** [comment]
Thanks, config seems fine. Does it work if you omit the proxy? Or is that not possible? Just want to rule out the proxy being the cause.

**Comment by aislaks** [comment]
```Error making request
Traceback (most recent call last):
  File "C:\Users\user\seleniumtest\.venv\lib\site-packages\seleniumwire\proxy\proxy2.py", line 91, in proxy_request
    conn.request(self.command, path, req_body, dict(req.headers))
  File "C:\Python36\lib\http\client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Python36\lib\http\client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Python36\lib\http\client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Python36\lib\http\client.py", line 1026, in _send_output
    self.send(msg)
  File "C:\Python36\lib\http\client.py", line 964, in send
    self.connect()
  File "C:\Users\user\seleniumtest\.venv\lib\site-packages\seleniumwire\proxy\proxy2.py", line 368, in connect
    super().connect()
  File "C:\Python36\lib\http\client.py", line 1400, in connect
    server_hostname=server_hostname)
  File "C:\Python36\lib\ssl.py", line 401, in wrap_socket
    _context=self, _session=session)
  File "C:\Python36\lib\ssl.py", line 808, in __init__
    self.do_handshake()
  File "C:\Python36\lib\ssl.py", line 1061, in do_handshake
    self._sslobj.do_handshake()
  File "C:\Python36\lib\ssl.py", line 683, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:749) ``` 

I had also been seeing this error for a while too. I did try without proxy, but I am facing the same error. Because of these 2 issues the browsers are closing before loading anything.

**Comment by aislaks** [comment]
![image](https://user-images.githubusercontent.com/39831772/95814418-fb92db00-0d37-11eb-8269-20c024bb4bd7.png)

I am using seleniumwire in windows 10 and this is the openssl version of the exe which comes with seleniumwire. Should I be checking for any other openssl?

**Comment by wkeeling** [comment]
OK thanks. I'll see if I can reproduce.

**Comment by aislaks** [comment]
Thanks, any help is appreciated, as in what could possibly cause these errors. I was thinking if it was giving a timeout which was causing the  "http.client.RemoteDisconnected: Remote end closed connection without response" error.

**Comment by aislaks** [comment]
Any updates on this?

**Comment by wkeeling** [comment]
Sorry for the delay on this.

I've tried reproducing the problem using a copy of your config (without the proxy section and the random user-agent), and the page seemed to load without any problem. I'm using Firefox 82.0.2, Python 3.7.3 on Windows 10 and geckodriver version 0.28.0-win64.

For reference, this is the test code:

```
def test_firefox_can_access_requests(self):
    seleniumwire_options = {
        # 'proxy': {
        #     'http': f'http://' + proxy,
        #     'https': f'https://' + proxy,
        # },
        'disable_encoding': True,
        'connection_timeout': 10 * 60,  # sec,
        'suppress_connection_errors': True,
        'ignore_http_methods': ['POST', 'OPTIONS']
    }

    capabilities = webdriver.DesiredCapabilities.FIREFOX
    capabilities['marionette'] = True
    # capabilities.update({'acceptInsecureCerts': True, 'acceptSslCerts': True})
    fp = FirefoxProfile()
    # fp.accept_untrusted_certs = True

    # fp.set_preference("general.useragent.override", 'MyUserAgent')
    # fp.set_preference("dom.webdriver.enabled", False)
    fp.set_preference('useAutomationExtension', False)
    fp.set_preference("excludeSwitches", "enable-automation")
    fp.set_preference("dom.webnotifications.enabled", False)
    fp.set_preference("geo.enabled", False)
    fp.set_preference("geo.prompt.testing", False)
    fp.set_preference("geo.prompt.testing.allow", False)
    fp.set_preference("permissions.default.image", 2)
    fp.update_preferences()
    browser = webdriver.Firefox(firefox_profile=fp, seleniumwire_options=seleniumwire_options)
    browser.get("https://google.com")
```

**Comment by wkeeling** [comment]
Do you get the same issue if you use Chrome?
