### ISSUE TITLE
ERROR:seleniumwire.proxy.handler:Error making request

### ISSUE THREAD

**Issue by shans0535** [wkeeling/selenium-wire#170]
ERROR:seleniumwire.proxy.handler:Error making request
Traceback (most recent call last):
  File "C:\Users\test\test32\lib\site-packages\seleniumwire\proxy\proxy2.py", line 101, in proxy_request
    res_body = res.read()
  File "C:\Users\test\AppData\Local\Programs\Python\Python38-32\lib\http\client.py", line 461, in read
    return self._readall_chunked()
  File "C:\Users\test\AppData\Local\Programs\Python\Python38-32\lib\http\client.py", line 568, in _readall_chunked
    chunk_left = self._get_chunk_left()
  File "C:\Users\test\AppData\Local\Programs\Python\Python38-32\lib\http\client.py", line 551, in _get_chunk_left
    chunk_left = self._read_next_chunk_size()
  File "C:\Users\test\AppData\Local\Programs\Python\Python38-32\lib\http\client.py", line 511, in _read_next_chunk_size
    line = self.fp.readline(_MAXLINE + 1)
  File "C:\Users\test\AppData\Local\Programs\Python\Python38-32\lib\socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "C:\Users\test\AppData\Local\Programs\Python\Python38-32\lib\ssl.py", line 1240, in recv_into
    return self.read(nbytes, buffer)
  File "C:\Users\test\AppData\Local\Programs\Python\Python38-32\lib\ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

**Comment by wkeeling** [comment]
Can you share the code that creates the webdriver and any options being passed.

**Comment by shans0535** [comment]
> 
> 
> Can you share the code that creates the webdriver and any options being passed.

from seleniumwire import webdriver
driver=webdriver.Firefox()
driver.get('https://www.cbtnuggets.com')

**Comment by wkeeling** [comment]
I'm not sure why you're seeing a timeout. It may be worth switching to the [mitmproxy backend](https://github.com/wkeeling/selenium-wire#backends) to see whether the timeout disappears. To switch the backend, install mitmproxy with:

```
pip install mitmproxy
```

Once installed, set the `backend` option in Selenium Wire's options to `mitmproxy`:

```
options = {
    'backend': 'mitmproxy'
}
driver = webdriver.Firefox(seleniumwire_options=options)
```

**Comment by shans0535** [comment]
Thanks for the response, let me try it!

**Comment by shans0535** [comment]
Awesome !!! it solved my issue 👍

**Comment by wkeeling** [comment]
Great to hear!

**Comment by shans0535** [comment]
Thanks for you help :) !!!
