### ISSUE TITLE
Getting Os error and page loading is super slow.

### ISSUE THREAD

**Issue by GeorgeTheodorak** [wkeeling/selenium-wire#172]
I am currently trying to acess a page using SeleniumWire proxy settings .
Here is the error i am currently having
I am using python 3.9 , running on windows with netspeed 90mbps

my code is 
path_to_driver = 'chromedriver.exe'
driver = webdriver.Chrome(
    path_to_driver,
    seleniumwire_options={'verify_ssl': False,'suppress_connection_errors': False, 'connection_timeout':None, 'proxy': {
        'https': '#i will not provide my proxy info here',
        'no_proxy': 'localhost,127.0.0.1'}})
driver.get('Just anxample page')

DevTools listening on ws://127.0.0.1:62787/devtools/browser/55a1529c-0eb8-453d-8b3b-209d8d9d1902
Error making request
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\seleniumwire\proxy\proxy2.py", line 91, in proxy_request
    conn.request(self.command, path, req_body, dict(req.headers))
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 1255, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 1301, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 1250, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 1010, in _send_output
    self.send(msg)
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 950, in send
    self.connect()
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\seleniumwire\proxy\proxy2.py", line 368, in connect
    super().connect()
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 1417, in connect
    super().connect()
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 926, in connect
    self._tunnel()
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 904, in _tunnel
    raise OSError("Tunnel connection failed: %d %s" % (code,
OSError: Tunnel connection failed: 502 Bad Gateway
[8224:228:1118/155315.800:ERROR:device_event_log_impl.cc(208)] [15:53:15.800] Bluetooth: bluetooth_adapter_winrt.cc:1076 Getting Default Adapter failed.
Error making request
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\seleniumwire\proxy\proxy2.py", line 91, in proxy_request
    conn.request(self.command, path, req_body, dict(req.headers))
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 1255, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 1301, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 1250, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 1010, in _send_output
    self.send(msg)
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 950, in send
    self.connect()
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\seleniumwire\proxy\proxy2.py", line 368, in connect
    super().connect()
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 1417, in connect
    super().connect()
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 926, in connect
    self._tunnel()
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 904, in _tunnel
    raise OSError("Tunnel connection failed: %d %s" % (code,
OSError: Tunnel connection failed: 502 Bad Gateway
Error making request
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\seleniumwire\proxy\proxy2.py", line 91, in proxy_request
    conn.request(self.command, path, req_body, dict(req.headers))
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 1255, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 1301, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 1250, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 1010, in _send_output
    self.send(msg)
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 950, in send
    self.connect()
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\seleniumwire\proxy\proxy2.py", line 368, in connect
    super().connect()
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 1417, in connect
    super().connect()
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 926, in connect
    self._tunnel()
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 904, in _tunnel
    raise OSError("Tunnel connection failed: %d %s" % (code,
OSError: Tunnel connection failed: 502 Bad Gateway
Error making request
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\seleniumwire\proxy\proxy2.py", line 91, in proxy_request
    conn.request(self.command, path, req_body, dict(req.headers))
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 1255, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 1301, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 1250, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 1010, in _send_output
    self.send(msg)
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 950, in send
    self.connect()
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\seleniumwire\proxy\proxy2.py", line 368, in connect
    super().connect()
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 1417, in connect
    super().connect()
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 926, in connect
    self._tunnel()
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 904, in _tunnel
    raise OSError("Tunnel connection failed: %d %s" % (code,
OSError: Tunnel connection failed: 502 Bad Gateway
Error making request
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\seleniumwire\proxy\proxy2.py", line 91, in proxy_request
    conn.request(self.command, path, req_body, dict(req.headers))
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 1255, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 1301, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 1250, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 1010, in _send_output
    self.send(msg)
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 950, in send
    self.connect()
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\seleniumwire\proxy\proxy2.py", line 368, in connect
    super().connect()
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 1417, in connect
    super().connect()
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 926, in connect
    self._tunnel()
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 904, in _tunnel
    raise OSError("Tunnel connection failed: %d %s" % (code,
OSError: Tunnel connection failed: 502 Bad Gateway

**Comment by wkeeling** [comment]
Can you try [switching the backend to mitmproxy](https://github.com/wkeeling/selenium-wire#backends) and see if that improves performance/fixes the 502.

To switch, first install mitmproxy with:

```
pip install mitmproxy
```

Once installed, add the `backend` option to your settings:
```
options = {
    'backend': 'mitmproxy',  # Set the backend to mitmproxy
    'verify_ssl': False,
    'suppress_connection_errors': False, 
    'connection_timeout':None, 
    'proxy': {
        'https': '#i will not provide my proxy info here',
        'no_proxy': 'localhost,127.0.0.1'
    }
}

driver = webdriver.Chrome(
    'chromedriver.exe',
    seleniumwire_options=options
)
```

**Comment by wkeeling** [comment]
@GeorgeTheodorak were you able to give the mitmproxy backend a try, and did it give you an improvement in performance?

**Comment by GeorgeTheodorak** [comment]
@wkeeling Yes , thanks very much i kinda forgot to reply .
Your solution works like charm !
Thanks.
