### ISSUE TITLE
Error in 0.9 since solving OPTION request issue

### ISSUE THREAD

**Issue by appunni-dishq** [wkeeling/selenium-wire#19]
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 57568)
----------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.5/socketserver.py", line 625, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.5/socketserver.py", line 354, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/home/user/.virtualenvs/project/lib/python3.5/site-packages/seleniumwire/proxy/proxy2.py", line 65, in __init__
    super().__init__(*args, **kwargs)
  File "/usr/lib/python3.5/socketserver.py", line 681, in __init__
    self.handle()
  File "/usr/lib/python3.5/http/server.py", line 424, in handle
    self.handle_one_request()
  File "/usr/lib/python3.5/http/server.py", line 410, in handle_one_request
    method()
  File "/home/user/.virtualenvs/project/lib/python3.5/site-packages/seleniumwire/proxy/proxy2.py", line 207, in do_GET
    res_body_modified = self.response_handler(req, req_body, res, res_body_plain)
  File "/home/user/.virtualenvs/project/lib/python3.5/site-packages/seleniumwire/proxy/handler.py", line 160, in response_handler
    self.server.storage.save_response(req.id, res, res_body)
AttributeError: 'CaptureRequestHandler' object has no attribute 'id'

**Comment by wkeeling** [comment]
Thanks - will resolve this ASAP.

**Comment by wkeeling** [comment]
@appunni-dishq this is fixed in 0.10.0 - now released. The issue was that Selenium Wire was trying to capture the response when the request was never captured.
