### ISSUE TITLE
Problem with selenoid and proxy auth.

### ISSUE THREAD

**Issue by shershen21** [wkeeling/selenium-wire#261]
In my tests, we need proxies with authorization, selenium-wire worked properly using Chrome on the local machine. Now I want to use the digitalocean droplet with selenoid. Selenoid does not work with an authorized proxy. But using selenoid with selenium-wire I can't get anywhere information and examples of how to connect 2 great products.

I attach the code:
https://www.notion.so/Sample-for-github-9f136fbe5c394f738d176edc3791672a

**Comment by wkeeling** [comment]
Adding the sample code to this issue:
```python
from seleniumwire import webdriver


def set_driver():
    proxy = 'xxx:xxx@91.215.226.234:65020'
    options = {'addr': '172.17.0.2',
        'proxy': {
            'http': f'socks5://{proxy}',
            'https': f'socks5://{proxy}',
            'no_proxy': 'localhost,172.17.0.2'
        }
    }

    capabilities = {
        "browserName": "chrome",
        "version": "80.0",
        "enableVNC": True,
        "enableVideo": False,
    }

    driver = webdriver.Remote(
        command_executor="http://139.59.000.00:4444/wd/hub", desired_capabilities=capabilities, seleniumwire_options=options)

    return driver


if __name__ == '__main__':
    driver = set_driver()
    driver.get('https://yandex.ru/internet')
    print(driver.page_source)
    driver.quit()


# Error example:

# Traceback (most recent call last):
#   File "/Users/alexg/PycharmProjects/selenium_test/venv/lib/python3.9/site-packages/seleniumwire/thirdparty/mitmproxy/server/server.py", line 41, in __init__
#     super().__init__(
#   File "/Users/alexg/PycharmProjects/selenium_test/venv/lib/python3.9/site-packages/seleniumwire/thirdparty/mitmproxy/net/tcp.py", line 594, in __init__
#     self.socket.bind(self.address)
# OSError: [Errno 49] Can't assign requested address

# The above exception was the direct cause of the following exception:

# Traceback (most recent call last):
#   File "/Users/alexg/PycharmProjects/selenium_test/main.py", line 290, in <module>
#     driver = set_driver()
#   File "/Users/alexg/PycharmProjects/selenium_test/main.py", line 254, in set_driver
#     driver = webdriver.Remote(
#   File "/Users/alexg/PycharmProjects/selenium_test/venv/lib/python3.9/site-packages/seleniumwire/webdriver.py", line 187, in __init__
#     self.proxy = backend.create(
#   File "/Users/alexg/PycharmProjects/selenium_test/venv/lib/python3.9/site-packages/seleniumwire/backend.py", line 35, in create
#     proxy = MitmProxy(addr, port, options)
#   File "/Users/alexg/PycharmProjects/selenium_test/venv/lib/python3.9/site-packages/seleniumwire/server.py", line 52, in __init__
#     self._master.server = ProxyServer(ProxyConfig(mitmproxy_opts))
#   File "/Users/alexg/PycharmProjects/selenium_test/venv/lib/python3.9/site-packages/seleniumwire/thirdparty/mitmproxy/server/server.py", line 49, in __init__
#     raise exceptions.ServerException(
# seleniumwire.thirdparty.mitmproxy.exceptions.ServerException: Error starting proxy server: OSError(49, "Can't assign requested address")
```

**Comment by wkeeling** [comment]
It looks as though Selenium Wire can't bind to `172.17.0.2`. Is this address definitely accessible within the environment that you're running Selenium Wire in? 

Whatever address you use must be publicly accessible because the remote Selenium instance running on 139.59.000.00 will need to talk back to it.

**Comment by shershen21** [comment]
I solved this problem in a radical way - I use a proxy with ip authorization.
