### ISSUE TITLE
seleniumwire throwing an error of 'noProxy' must be a string

### ISSUE THREAD

**Issue by Danyalm66** [wkeeling/selenium-wire#271]
I don't know why but yesterday night, seleniumwire was working perfect but from today morning, I am getting two issue one with `executable_path` and one without path. Error stack for both problems are shown below.

**Yesterday, it was working perfect without `executable_path` but now getting this error:**
```

>>> driver = webdriver.Chrome()
Traceback (most recent call last):
  File "/home/danial/.local/lib/python3.8/site-packages/selenium/webdriver/common/service.py", line 72, in start
    self.process = subprocess.Popen(cmd, env=self.env,
  File "/usr/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: './chromedriver'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/danial/.local/lib/python3.8/site-packages/undetected_chromedriver/__init__.py", line 53, in __new__
    instance.__init__(*args, **kwargs)
  File "/home/danial/.local/lib/python3.8/site-packages/seleniumwire/webdriver.py", line 114, in __init__
    super().__init__(*args, **kwargs)
  File "/home/danial/.local/lib/python3.8/site-packages/selenium/webdriver/chrome/webdriver.py", line 73, in __init__
    self.service.start()
  File "/home/danial/.local/lib/python3.8/site-packages/selenium/webdriver/common/service.py", line 86, in start
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable may have wrong permissions. Please see https://sites.google.com/a/chromium.org/chromedriver/home

```

**And with `executable_path`, getting this error**
```


>>> driver = webdriver.Chrome(executable_path = '/usr/bin/chromedriver')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/danial/.local/lib/python3.8/site-packages/undetected_chromedriver/__init__.py", line 53, in __new__
    instance.__init__(*args, **kwargs)
  File "/home/danial/.local/lib/python3.8/site-packages/seleniumwire/webdriver.py", line 114, in __init__
    super().__init__(*args, **kwargs)
  File "/home/danial/.local/lib/python3.8/site-packages/selenium/webdriver/chrome/webdriver.py", line 76, in __init__
    RemoteWebDriver.__init__(
  File "/home/danial/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/home/danial/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/home/danial/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/danial/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot parse capability: proxy
from unknown error: 'noProxy' must be a string
  (Driver info: chromedriver=2.41.578700 (2f1ed5f9343c13f73144538f15c00b370eda6706),platform=Linux 5.8.0-50-generic x86_64)
```

I tested this `executable_path` with `undetected_chromedriver` and it's working their. So the problem doesn't seem to be with path.

**Comment by wkeeling** [comment]
The first error looks as though it's just a permissions issue. Have you checked that the chromedriver in the current working directory `./chromedriver` has execute permission? My chromedriver has the permissions 755:

```
-rwxr-xr-x
```

The second error is occurring because the version of chromedriver is too old (v2.41.578700) and is not compatible with Selenium Wire. Upgrading it to a [newer version](https://chromedriver.chromium.org/downloads) should fix.
