### ISSUE TITLE
ValueError: Different settings for http and https proxy servers not supported

### ISSUE THREAD

**Issue by svurgun** [wkeeling/selenium-wire#282]
I am trying to add Authorization header to selenium tests by setting an request_interceptor function like mentioned <a href="https://stackoverflow.com/a/51919307/" target="_blank">here</a> 
```
from seleniumwire import webdriver
    # Create a new instance of the Firefox driver (or Chrome)
    driver = webdriver.Chrome()
    # Create a request interceptor
    def interceptor(request):
        del request.headers['Authorization']  # Delete the header first
        request.headers['Authorization'] = 'Bearer lkjsdfaljf ...'
    # Set the interceptor on the driver
    driver.request_interceptor = interceptor
    driver.get('https://some-url')
```
When I run the code, I am getting a ValueError below. Is there any way to get around this?

Traceback (most recent call last): 
File "c:\Projects\Selenium\Tests\Test_HomePage.py", line 42, in setUpClass self.driver = create_driver_seleniumwire() 
File "c:\Projects\Selenium\Tests\Test_HomePage.py", line 29, in create_driver_seleniumwire driver = webdriver.Chrome() 
File "C:\Users\abc\AppData\Roaming\Python\Python39\site-packages\seleniumwire\webdriver.py", line 90, in __init__ self.proxy = backend.create( File "C:\Users\abc\AppData\Roaming\Python\Python39\site-packages\seleniumwire\backend.py", line 35, in create proxy = MitmProxy(addr, port, options) 
File "C:\Users\abc\AppData\Roaming\Python\Python39\site-packages\seleniumwire\server.py", line 63, in __init__ **self._get_upstream_proxy_args(), 
File "C:\Users\abc\AppData\Roaming\Python\Python39\site-packages\seleniumwire\server.py", line 97, in _get_upstream_proxy_args raise ValueError('Different settings for http and https proxy servers not supported') 
**ValueError: Different settings for http and https proxy servers not supported**

Thank you! [](url)

**Comment by wkeeling** [comment]
The error implies that you have an upstream proxy server configured. Are you passing any configuration to the Chrome driver that isn't shown in the example code above?

**Comment by svurgun** [comment]
I wasn't setting anything in the code but I had environment variables set. Once I removed them, it worked. Thank you for the quick response.
