### ISSUE TITLE
Is selenium-wire thread-safe?

### ISSUE THREAD

**Issue by chwba** [wkeeling/selenium-wire#293]
Im using it multithreaded with proxies (with auth). First it will spam: `Invalid proxy server credentials supplied` and afterwards a lot of the following:

```
127.0.0.1:62525: Traceback (most recent call last):
  File "C:\Users\Administrator\git\selenium_gen\venv\lib\site-packages\seleniumwire\thirdparty\mitmproxy\net\tcp.py", line 115, in read
    data = self.o.read(rlen)
  File "C:\Users\Administrator\.pyenv\pyenv-win\versions\3.9.5\lib\socket.py", line 704, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Administrator\git\selenium_gen\venv\lib\site-packages\seleniumwire\thirdparty\mitmproxy\server\server.py", line 113, in handle
    root_layer()
  File "C:\Users\Administrator\git\selenium_gen\venv\lib\site-packages\seleniumwire\thirdparty\mitmproxy\server\modes\http_proxy.py", line 23, in __call__
    layer()
  File "C:\Users\Administrator\git\selenium_gen\venv\lib\site-packages\seleniumwire\thirdparty\mitmproxy\server\protocol\tls.py", line 285, in __call__
    layer()
  File "C:\Users\Administrator\git\selenium_gen\venv\lib\site-packages\seleniumwire\thirdparty\mitmproxy\server\protocol\http1.py", line 100, in __call__
    layer()
  File "C:\Users\Administrator\git\selenium_gen\venv\lib\site-packages\seleniumwire\thirdparty\mitmproxy\server\protocol\http.py", line 205, in __call__
    if not self._process_flow(flow):
  File "C:\Users\Administrator\git\selenium_gen\venv\lib\site-packages\seleniumwire\thirdparty\mitmproxy\server\protocol\http.py", line 283, in _process_flow
    request: http.HTTPRequest = self.read_request_headers(f)
  File "C:\Users\Administrator\git\selenium_gen\venv\lib\site-packages\seleniumwire\thirdparty\mitmproxy\server\protocol\http1.py", line 13, in read_request_headers
    return http1.read_request_head(self.client_conn.rfile)
  File "C:\Users\Administrator\git\selenium_gen\venv\lib\site-packages\seleniumwire\thirdparty\mitmproxy\net\http\http1\read.py", line 51, in read_request_head
    headers = _read_headers(rfile)
  File "C:\Users\Administrator\git\selenium_gen\venv\lib\site-packages\seleniumwire\thirdparty\mitmproxy\net\http\http1\read.py", line 321, in _read_headers
    line = rfile.readline()
  File "C:\Users\Administrator\git\selenium_gen\venv\lib\site-packages\seleniumwire\thirdparty\mitmproxy\net\tcp.py", line 157, in readline
    ch = self.read(1)
  File "C:\Users\Administrator\git\selenium_gen\venv\lib\site-packages\seleniumwire\thirdparty\mitmproxy\net\tcp.py", line 135, in read
    raise exceptions.TcpDisconnect(str(e))
seleniumwire.thirdparty.mitmproxy.exceptions.TcpDisconnect: [WinError 10054] An existing connection was forcibly closed by the remote host
```

The credentials for these proxies are variable (luminati.io), they are correct and some of the threads actually work properly but the majority will drop the exceptions mentioned above.

EDIT: While experimenting I tried to switch the backend to mitmproxy and now im getting `127.0.0.1:1684: Client Handshake failed. The client may not trust the proxy's certificate for targetdomain.com.`. I have tried to add `--ignore-certificate-errors-spki-list` and `--ignore-ssl-errors` to the chrome_options and `'upstream_cert': False` to the selenium-wire options but that did not help yet, any advice?

**Comment by wkeeling** [comment]
Thanks for raising this. Do you get the above exceptions if you run with a single thread, or does that always work reliably?

With the mitmproxy backend, you can try adding the `mitmproxy-ca-cert.pem` to your browser which should make the "The client may not trust the proxy's certificate" error disappear. You should be able to find the certificate in the `.mitmproxy` folder in your home folder (I guess `C:\Users\Administrator`?).

**Comment by chwba** [comment]
In a single thread everything is perfectly stable! Thank you for the hint regarding the cert - I followed https://docs.mitmproxy.org/stable/concepts-certificates/#installing-the-mitmproxy-ca-certificate-manually but with that I can only add mitm-proxy-ca-cert.cer - Then I followed https://support.globalsign.com/digital-certificates/digital-certificate-installation/install-client-digital-certificate-windows-using-chrome and added it in all my browsers, didnt seem to fix it properly, what could I be doing wrong?

**Comment by wkeeling** [comment]
Sorry for the delay in replying and thanks for the extra info about the setting the event loop. I'll look at reproducing this on Windows and see if figure out the problem. There are [other issues](https://github.com/wkeeling/selenium-wire/issues/280) reporting problems with threads, so it's possible that there is a fundamental problem running multi-threaded.

**Comment by HMaker** [comment]
> Sorry for the delay in replying and thanks for the extra info about the setting the event loop. I'll look at reproducing this on Windows and see if figure out the problem. There are [other issues](https://github.com/wkeeling/selenium-wire/issues/280) reporting problems with threads, so it's possible that there is a fundamental problem running multi-threaded.

are there any global state kept by seleniumwire? It could use random ports and spin up a proxy server for each driver instance.

**Comment by wkeeling** [comment]
There's now a fix for proxy authorization failures when running multi-threaded in v4.3.3. If you have a chance to try it and let me know how it goes I'd appreciate it!
