### ISSUE TITLE
Gevent Support

### ISSUE THREAD

**Issue by yo-bur** [wkeeling/selenium-wire#301]
Hi, I'm trying to use `selenium-wire` in a project that has been _monkey-patched_ with [gevent](https://www.gevent.org/) and I'm running into an issue loading _HTTPS_ sites. Plan _HTTP_ sites seem to work as intended.

I've created the following simple script that can reproduce the behaviour:
```
from gevent import monkey
monkey.patch_all()

from seleniumwire.webdriver import Chrome, ChromeOptions
from selenium.webdriver import DesiredCapabilities

chrome_options = ChromeOptions()
chrome_options.add_argument("--no-sandbox")
chrome_options.add_argument("--headless")

cap = DesiredCapabilities.CHROME
driver = Chrome(
    options=chrome_options,
    desired_capabilities=cap
)

def interceptor(request, response):
    print(request)

driver.response_interceptor = interceptor
driver.get("https://example.com")

print(driver.page_source)
print("done")
```

Output for *HTTPS* site (`https://example.com`):
```
$ python test2.py 
<html><head></head><body></body></html>
done
```

Output for *HTTP* site (`http://example.com`):
```
$ python test2.py 
http://example.com/
<html><head>
    <title>Example Domain</title>

    ... removed full response for simplicity.

</html>
done
```

As you can see from the output, the `interceptor` method is not getting called as it's not printing the request for the _HTTPS_ site. The driver's `page_source` is also empty (`<html><head></head><body></body></html>`).

Also interestingly, if the same script is changed to import the `undetected-chromedriver` instead, an `ERR_SSL_PROTOCOL_ERROR` error is raised for _HTTPS_ sites. _HTTP_ sites still behave as intended.
```
from seleniumwire.undetected_chromedriver.v2 import Chrome, ChromeOptions
```

Output:
```
$ python test2.py 
Traceback (most recent call last):
  File "test2.py", line 28, in <module>
    driver.get("https://example.com")
  File "/home/johann/pyenv/my-env/lib/python3.8/site-packages/undetected_chromedriver/v2.py", line 383, in get_wrapped
    return orig_get(*args, **kwargs)
  File "/home/johann/pyenv/my-env/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/johann/pyenv/my-env/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/johann/pyenv/my-env/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_SSL_PROTOCOL_ERROR
  (Session info: headless chrome=90.0.4430.72)
```

I have also tried using the `mitmproxy` backend which produced the same behaviour.

Are you able to provide any direction to get `selenium-wire` working with gevent, or have any insight into what exactly is causing the issue?

---
Running in WSL2 on 64bit Windows.
Python: v3.8.0
Selenium: v3.141.0
Selenium Wire: v4.3.0
Chrome: v90.0.4430.72

**Comment by lsl-2020** [comment]
Yes. I have just met the exact same issue with gevent, Selenium Wire, Firefox and geckodriver. 

Hope this can be fixed soon.

**Comment by adv-zl** [comment]
Faced with same issue. Django + celery project, celery runs with -P gevent key causes same problems.

from gevent import monkey
monkey.patch_all()

Helps to fix selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_CLOSED
but returns empty page. Any solutions for this?
