### ISSUE TITLE
ca cert not found for compiled python script

### ISSUE THREAD

**Issue by CheemaOTB** [wkeeling/selenium-wire#310]
I compiled a python script that was using selenium wire so that my friend could use it but he gets this error.

```python
[21:41:56.795873] [Task 1] An Error Occured
Exception in thread Thread-1:
Traceback (most recent call last):
  File "<frozen ssense>", line 318, in main
  File "undetected_chromedriver__init.py", line 53, in new
  File "seleniumwire\webdriver.py", line 90, in init
  File "seleniumwire\backend.py", line 35, in create
  File "seleniumwire\server.py", line 28, in init__
  File "seleniumwire\utils.py", line 95, in extract_cert_and_key
  File "pkgutil.py", line 638, in get_data
  File "PyInstaller\loader\pyimod03_importers.py", line 365, in get_data
FileNotFoundError: [Errno 2] No such file or directory: 'C:\Users\ower\AppData\Local\Temp\_MEI115042\seleniumwire\ca.crt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "threading.py", line 950, in _bootstrap_inner
  File "threading.py", line 888, in run
  File "<frozen ssense>", line 327, in main
UnboundLocalError: local variable 'driver' referenced before assignment
```

**Comment by OliverTrust** [comment]
Same problem 
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Users\ADMINI~1\AppData\Local\ins_soft\AXO2MO~1\021~1.0\threading.py", line 954, in _bootstrap_inner
  File "C:\Users\ADMINI~1\AppData\Local\ins_soft\AXO2MO~1\021~1.0\threading.py", line 892, in run
  File "C:\Users\ADMINI~1\AppData\Local\ins_soft\AXO2MO~1\021~1.0\axo2moon.py", line 136, in claim_axo
  File "C:\Users\ADMINI~1\AppData\Local\ins_soft\AXO2MO~1\021~1.0\axo2moon.py", line 113, in prepare_driver
  File "C:\Users\ADMINI~1\AppData\Local\ins_soft\AXO2MO~1\021~1.0\seleniumwire\undetected_chromedriver\v2.py", line 27, in __init__
  File "C:\Users\ADMINI~1\AppData\Local\ins_soft\AXO2MO~1\021~1.0\seleniumwire\backend.py", line 35, in create
  File "C:\Users\ADMINI~1\AppData\Local\ins_soft\AXO2MO~1\021~1.0\seleniumwire\server.py", line 28, in __init__
  File "C:\Users\ADMINI~1\AppData\Local\ins_soft\AXO2MO~1\021~1.0\seleniumwire\utils.py", line 95, in extract_cert_and_key
  File "C:\Users\ADMINI~1\AppData\Local\ins_soft\AXO2MO~1\021~1.0\pkgutil.py", line 638, in get_data
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\ADMINI~1\\AppData\\Local\\ins_soft\\AXO2MO~1\\021~1.0\\seleniumwire\\ca.crt'
Exception ignored in: <compiled_function Chrome.__del__ at 0x0000000008BFA4F0>
Traceback (most recent call last):
  File "C:\Users\ADMINI~1\AppData\Local\ins_soft\AXO2MO~1\021~1.0\undetected_chromedriver\v2.py", line 590, in __del__
  File "C:\Users\ADMINI~1\AppData\Local\ins_soft\AXO2MO~1\021~1.0\seleniumwire\webdriver.py", line 46, in quit
AttributeError: 'Chrome' object has no attribute 'proxy'

**Comment by OliverTrust** [comment]
my monkey solution: add `ca.crt` and `ca.key` from https://github.com/wkeeling/selenium-wire/tree/master/seleniumwire in soft AppData folder

**Comment by CheemaOTB** [comment]
> My dirty solution: add `ca.crt` and `ca.key` from https://github.com/wkeeling/selenium-wire/tree/master/seleniumwire in soft AppData folder

Did you put it in this directory "C:\Users\Owner\AppData\Roaming"?

**Comment by binchoo** [comment]
@CheemaOTB 
Hello, I am also hearing from some users that they are experiencing the same issue. Where should `ca.crt` and `ca.key` be placed?

**Comment by binchoo** [comment]
### Solution
Make Pyinstaller include `seleniumwire`'s `ca.crt` and `ca.key` manually.
We can do this by editing the `.spec` file created by `pyi-makespec`. (See, [Using Spec Files](https://pyinstaller.readthedocs.io/en/stable/spec-files.html))

Inject the list of resources that need to be included, to `datas` of `Analysis`.
```python
from os.path import join, dirname, abspath, split
from os import sep
import glob
import seleniumwire

pkg_dir = split(seleniumwire.__file__)[0]
pkg_data = []
pkg_data.extend((file, dirname(file).split("site-packages")[1]) for file in glob.iglob(join(pkg_dir,"**{}*".format(sep)), recursive=True))

a = Analysis([f'..{os.sep}qtmain.py'],
             pathex=['F:\\repositories\\corona-virus-vaccine-reservation'],
             binaries=[],
             datas=pkg_data,
             hiddenimports=[],
```
(See, one of its [use case](https://github.com/binchoo/selenium-kakao-vaccine-reservation/blob/fffb61a4e6114c9c1dbcd749215f59c365a2bbea/dist/window-build.spec#L5-L18))
