### ISSUE TITLE
mitmproxy errors essentially at random

### ISSUE THREAD

**Issue by jidar** [wkeeling/selenium-wire#361]
Exception in thread Http2SingleStreamLayer-15:
Traceback (most recent call last):
  File "/home/jidar/venvs/project/lib/python3.8/site-packages/h2/connection.py", line 590, in _get_or_create_stream
    return self.streams[stream_id]
KeyError: 15

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
Exception in thread Http2SingleStreamLayer-19:
Traceback (most recent call last):
  File "/home/jidar/venvs/project/lib/python3.8/site-packages/h2/stream.py", line 117, in process_input
    func, target_state = _transitions[(self.state, input_)]
    self.run()
KeyError: (<StreamState.HALF_CLOSED_LOCAL: 5>, <StreamInputs.SEND_HEADERS: 0>)
  File "/home/jidar/venvs/project/lib/python3.8/site-packages/seleniumwire/thirdparty/mitmproxy/server/protocol/http2.py", line 719, in run

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
    layer()
  File "/home/jidar/venvs/project/lib/python3.8/site-packages/seleniumwire/thirdparty/mitmproxy/server/protocol/http2.py", line 719, in run
  File "/home/jidar/venvs/project/lib/python3.8/site-packages/seleniumwire/thirdparty/mitmproxy/server/protocol/http.py", line 206, in __call__
    layer()
  File "/home/jidar/venvs/project/lib/python3.8/site-packages/seleniumwire/thirdparty/mitmproxy/server/protocol/http.py", line 206, in __call__
    if not self._process_flow(flow):
  File "/home/jidar/venvs/project/lib/python3.8/site-packages/seleniumwire/thirdparty/mitmproxy/server/protocol/http.py", line 388, in _process_flow
    if not self._process_flow(flow):
  File "/home/jidar/venvs/project/lib/python3.8/site-packages/seleniumwire/thirdparty/mitmproxy/server/protocol/http.py", line 388, in _process_flow
    get_response()
    get_response()
  File "/home/jidar/venvs/project/lib/python3.8/site-packages/seleniumwire/thirdparty/mitmproxy/server/protocol/http.py", line 373, in get_response
  File "/home/jidar/venvs/project/lib/python3.8/site-packages/seleniumwire/thirdparty/mitmproxy/server/protocol/http.py", line 373, in get_response
    self.send_request_headers(f.request)
  File "/home/jidar/venvs/project/lib/python3.8/site-packages/seleniumwire/thirdparty/mitmproxy/server/protocol/http2.py", line 389, in wrapper
    self.send_request_headers(f.request)
    result = func(self, *args, **kwargs)
  File "/home/jidar/venvs/project/lib/python3.8/site-packages/seleniumwire/thirdparty/mitmproxy/server/protocol/http2.py", line 389, in wrapper
  File "/home/jidar/venvs/project/lib/python3.8/site-packages/seleniumwire/thirdparty/mitmproxy/server/protocol/http2.py", line 609, in send_request_headers
    raise e
  File "/home/jidar/venvs/project/lib/python3.8/site-packages/seleniumwire/thirdparty/mitmproxy/server/protocol/http2.py", line 599, in send_request_headers
    result = func(self, *args, **kwargs)
  File "/home/jidar/venvs/project/lib/python3.8/site-packages/seleniumwire/thirdparty/mitmproxy/server/protocol/http2.py", line 609, in send_request_headers
    self.connections[self.server_conn].safe_send_headers(
  File "/home/jidar/venvs/project/lib/python3.8/site-packages/seleniumwire/thirdparty/mitmproxy/server/protocol/http2.py", line 53, in safe_send_headers
    raise e
  File "/home/jidar/venvs/project/lib/python3.8/site-packages/seleniumwire/thirdparty/mitmproxy/server/protocol/http2.py", line 599, in send_request_headers
    self.send_headers(stream_id, headers.fields, **kwargs)
  File "/home/jidar/venvs/project/lib/python3.8/site-packages/h2/connection.py", line 767, in send_headers
    self.connections[self.server_conn].safe_send_headers(
    stream = self._get_or_create_stream(
  File "/home/jidar/venvs/project/lib/python3.8/site-packages/seleniumwire/thirdparty/mitmproxy/server/protocol/http2.py", line 53, in safe_send_headers
  File "/home/jidar/venvs/project/lib/python3.8/site-packages/h2/connection.py", line 592, in _get_or_create_stream
    self.send_headers(stream_id, headers.fields, **kwargs)
  File "/home/jidar/venvs/project/lib/python3.8/site-packages/h2/connection.py", line 770, in send_headers
    return self._begin_new_stream(stream_id, allowed_ids)
  File "/home/jidar/venvs/project/lib/python3.8/site-packages/h2/connection.py", line 477, in _begin_new_stream
    frames = stream.send_headers(
  File "/home/jidar/venvs/project/lib/python3.8/site-packages/h2/stream.py", line 863, in send_headers
    self.config.logger.debug("Current streams: %s", self.streams.keys())
  File "/home/jidar/venvs/project/lib/python3.8/site-packages/seleniumwire/thirdparty/mitmproxy/server/protocol/http2.py", line 96, in debug
    events = self.state_machine.process_input(input_)
  File "/home/jidar/venvs/project/lib/python3.8/site-packages/h2/stream.py", line 121, in process_input
    self.log(msg, "debug")
  File "/home/jidar/venvs/project/lib/python3.8/site-packages/seleniumwire/thirdparty/mitmproxy/server/root_context.py", line 121, in log
    raise ProtocolError(
h2.exceptions.ProtocolError: Invalid input StreamInputs.SEND_HEADERS in state StreamState.HALF_CLOSED_LOCAL
    self.channel.tell("log", log.LogEntry(full_msg, level))
  File "/home/jidar/venvs/project/lib/python3.8/site-packages/seleniumwire/thirdparty/mitmproxy/controller.py", line 43, in tell
    asyncio.run_coroutine_threadsafe(
  File "/usr/lib/python3.8/asyncio/tasks.py", line 930, in run_coroutine_threadsafe
    loop.call_soon_threadsafe(callback)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 764, in call_soon_threadsafe
    self._check_closed()
  File "/usr/lib/python3.8/asyncio/base_events.py", line 508, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
/usr/lib/python3.8/threading.py:934: RuntimeWarning: coroutine 'AddonManager.handle_lifecycle' was never awaited
  self._invoke_excepthook(self)
RuntimeWarning: Enable tracemalloc to get the object allocation traceback

**Comment by wkeeling** [comment]
Thanks for raising this. 

Are you able to post some code that demonstrates the problem? It looks like your using Linux? Can you let me know what distro/version?

**Comment by jidar** [comment]
Ubuntu 20.04Ubuntu 20.04.2 LTS
selenium==3.141.0
selenium-wire==4.4.0

I'm working on a standalone toy example that reproduces it.  Currently I'm only seeing it in roughly one out of a hundred test runs, essentially at random.

**Comment by wkeeling** [comment]
Closing due to inactivity.
