### ISSUE TITLE
Full Traceback Displayed Reporting [WinError 10053] An established connection was aborted by the software in your host machine

### ISSUE THREAD

**Issue by theohgr** [wkeeling/selenium-wire#362]
Receiving infrequent connection errors with a full traceback:

 [WinError 10053] An established connection was aborted by the software in your host machine

The errors appear to be retried, and do not effect performance of the scraper, but I'd like to suppress the errors to cleanup the output. 

This seems similar to a closed issue I found:

https://github.com/wkeeling/selenium-wire/issues/230

selenium-wire is version 4.4.0.  I've suppressed connection errors, but it still bubbles up:

```
 selenium_wire_options = {
        'suppress_connection_errors': True
    }

```
`127.0.0.1:50778: Traceback (most recent call last):
  File "seleniumwire\thirdparty\mitmproxy\net\tcp.py", line 94, in write
    r = self.o.write(v)
  File "socket.py", line 722, in write
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "seleniumwire\thirdparty\mitmproxy\server\server.py", line 113, in handle
    root_layer()
  File "seleniumwire\thirdparty\mitmproxy\server\modes\http_proxy.py", line 23, in __call__
    layer()
  File "seleniumwire\thirdparty\mitmproxy\server\protocol\tls.py", line 285, in __call__
    layer()
  File "seleniumwire\thirdparty\mitmproxy\server\protocol\http1.py", line 100, in __call__
    layer()
  File "seleniumwire\thirdparty\mitmproxy\server\protocol\http.py", line 206, in __call__
    if not self._process_flow(flow):
  File "seleniumwire\thirdparty\mitmproxy\server\protocol\http.py", line 288, in _process_flow
    return self.handle_upstream_connect(f)
  File "seleniumwire\thirdparty\mitmproxy\server\protocol\http.py", line 251, in handle_upstream_connect
    self.send_response(f.response)
  File "seleniumwire\thirdparty\mitmproxy\server\protocol\http.py", line 54, in send_response
    self.send_response_body(response, [response.data.content])
  File "seleniumwire\thirdparty\mitmproxy\server\protocol\http1.py", line 72, in send_response_body
    self.client_conn.wfile.write(chunk)
  File "seleniumwire\thirdparty\mitmproxy\net\tcp.py", line 98, in write
    raise exceptions.TcpDisconnect(str(e))
seleniumwire.thirdparty.mitmproxy.exceptions.TcpDisconnect: [WinError 10053] An established connection was aborted by the software in your host machine`

**Comment by wkeeling** [comment]
Thanks for this. I'll see if I can quieten these messages.

**Comment by wkeeling** [comment]
This seems to be a bug introduced in version 4.3.3. A short term fix is to downgrade to 4.3.2:

```
pip install selenium-wire==4.3.2
```

Related to #389

**Comment by makarworld** [comment]
Not fixed yet. I still get this error.
My case:

```python
import json
from seleniumwire import webdriver
from seleniumwire.utils import decode
from selenium.webdriver.chrome.service import Service as ChromeService

options = {
    'proxy': {
        'http': "http://login:password@0.0.0.0:0",
        'https': "http://login:password@0.0.0.0:0",
        'no_proxy': 'localhost,127.0.0.1'
    }
}

driver = webdriver.Chrome(service = ChromeService(r'Z:\\chromedriver.exe'), seleniumwire_options = options)
driver.set_window_size(1, 1)

driver.get("https://example.com")

for request in driver.requests:
    if "some_pattern" in request.url:
        if request.response is None:
            continue
        body = decode(request.response.body, request.response.headers.get('Content-Encoding', 'identity'))
        resp = json.loads(body.decode('utf-8'))
        break
else:
    resp = None 

driver.close()
```
Error:
```
127.0.0.1:52708: Traceback (most recent call last):
  File "C:\Python310\lib\site-packages\seleniumwire\thirdparty\mitmproxy\net\tcp.py", line 94, in write
    r = self.o.write(v)
  File "C:\Python310\lib\socket.py", line 723, in write
    return self._sock.send(b)
ConnectionResetError: [WinError 10054] Удаленный хост принудительно разорвал существующее подключение

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python310\lib\site-packages\seleniumwire\thirdparty\mitmproxy\server\server.py", line 113, in handle
    root_layer()
  File "C:\Python310\lib\site-packages\seleniumwire\thirdparty\mitmproxy\server\modes\http_proxy.py", line 23, in __call__
    layer()
  File "C:\Python310\lib\site-packages\seleniumwire\thirdparty\mitmproxy\server\protocol\tls.py", line 285, in __call__
    layer()
  File "C:\Python310\lib\site-packages\seleniumwire\thirdparty\mitmproxy\server\protocol\http1.py", line 100, in __call__
    layer()
  File "C:\Python310\lib\site-packages\seleniumwire\thirdparty\mitmproxy\server\protocol\http.py", line 206, in __call__
    if not self._process_flow(flow):
  File "C:\Python310\lib\site-packages\seleniumwire\thirdparty\mitmproxy\server\protocol\http.py", line 288, in _process_flow
    return self.handle_upstream_connect(f)
  File "C:\Python310\lib\site-packages\seleniumwire\thirdparty\mitmproxy\server\protocol\http.py", line 251, in handle_upstream_connect
    self.send_response(f.response)
  File "C:\Python310\lib\site-packages\seleniumwire\thirdparty\mitmproxy\server\protocol\http.py", line 53, in send_response
    self.send_response_headers(response)
  File "C:\Python310\lib\site-packages\seleniumwire\thirdparty\mitmproxy\server\protocol\http1.py", line 67, in send_response_headers
    self.client_conn.wfile.write(raw)
  File "C:\Python310\lib\site-packages\seleniumwire\thirdparty\mitmproxy\net\tcp.py", line 98, in write
    raise exceptions.TcpDisconnect(str(e))
seleniumwire.thirdparty.mitmproxy.exceptions.TcpDisconnect: [WinError 10054] Удаленный хост принудительно разорвал существующее подключение
```
