### ISSUE TITLE
selenium wire errors with multithreading

### ISSUE THREAD

**Issue by jordibonastrem** [wkeeling/selenium-wire#383]
Hi, selenium wire is working fine with one thread, but when i try to run multiple threads this error is shown

```
Traceback (most recent call last):
  File "C:\Users\Usuario\AppData\Roaming\Python\Python38\site-packages\seleniumwire\thirdparty\mitmproxy\server\server.py", line 113, in handle
    root_layer()
  File "C:\Users\Usuario\AppData\Roaming\Python\Python38\site-packages\seleniumwire\thirdparty\mitmproxy\server\modes\http_proxy.py", line 23, in __call__
    layer()
  File "C:\Users\Usuario\AppData\Roaming\Python\Python38\site-packages\seleniumwire\thirdparty\mitmproxy\server\protocol\tls.py", line 
285, in __call__
    layer()
  File "C:\Users\Usuario\AppData\Roaming\Python\Python38\site-packages\seleniumwire\thirdparty\mitmproxy\server\protocol\http1.py", line 100, in __call__
    layer()
  File "C:\Users\Usuario\AppData\Roaming\Python\Python38\site-packages\seleniumwire\thirdparty\mitmproxy\server\protocol\http.py", line 206, in __call__
    if not self._process_flow(flow):
  File "C:\Users\Usuario\AppData\Roaming\Python\Python38\site-packages\seleniumwire\thirdparty\mitmproxy\server\protocol\http.py", line 288, in _process_flow
    return self.handle_upstream_connect(f)
  File "C:\Users\Usuario\AppData\Roaming\Python\Python38\site-packages\seleniumwire\thirdparty\mitmproxy\server\protocol\http.py", line 251, in handle_upstream_connect
    self.send_response(f.response)
  File "C:\Users\Usuario\AppData\Roaming\Python\Python38\site-packages\seleniumwire\thirdparty\mitmproxy\server\protocol\http.py", line 54, in send_response
    self.send_response_body(response, [response.data.content])
  File "C:\Users\Usuario\AppData\Roaming\Python\Python38\site-packages\seleniumwire\thirdparty\mitmproxy\server\protocol\http1.py", line 72, in send_response_body
    self.client_conn.wfile.write(chunk)
  File "C:\Users\Usuario\AppData\Roaming\Python\Python38\site-packages\seleniumwire\thirdparty\mitmproxy\net\tcp.py", line 98, in write    raise exceptions.TcpDisconnect(str(e))
seleniumwire.thirdparty.mitmproxy.exceptions.TcpDisconnect: [WinError 10053] Se ha anulado una conexión establecida por el software en 
su equipo host

```
Im using ThreadPoolExecutor to generate threads

```
with concurrent.futures.ThreadPoolExecutor() as executor:
                    for taskid in range(int(CREDENTIALS.TASK_NUM)):
                        
                        self.choseProxie(taskid)
                        executor.submit(self.startTask,taskid)
```

What can i do to solve it ??

**Comment by wkeeling** [comment]
This looks as though it's caused by a bug introduced in version 4.3.3. As a short term fix you may be able to resolve the problem by downgrading:

```
pip install selenium-wire==4.3.2
```

Related to #389
