### ISSUE TITLE
[WinError 10053] An established connection was aborted by the software in your host machine

### ISSUE THREAD

**Issue by kingAli110** [wkeeling/selenium-wire#389]
I have recently began to get this issue 
`
TypeError: __init__() got an unexpected keyword argument 'seleniumwire_options'
` 
in the following code:

`driver = webdriver.Chrome(desired_capabilities=capabilities, executable_path=r"C:\Users\ali\Desktop\chromedriver.exe", seleniumwire_options=server, options=chrome_options)
`

My selenium wire version is 4.5.2, selenium version is 3.141.0 and chrome version is 93.0.4577.63

**Comment by wkeeling** [comment]
Thanks for the issue. 

Can you show all the code, including the imports you're using? The error indicates that selenium wire's webdriver is not being used.

**Comment by kingAli110** [comment]
```
from seleniumwire import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
import time
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from selenium.webdriver.common.action_chains import ActionChains
import random
import proxy_handling
from selenium.webdriver.common.keys import Keys
from getgoal import brownian_motion

proxy_number = random.randint(0, 100)
print(proxy_number)

# proxy setup
server = {
    'proxy': {
        'http': proxy_handling.http_proxy(proxy_number),
        'https': proxy_handling.https_proxy(proxy_number),
        'no_proxy': 'localhost,127.0.0.1'
    }
}

chrome_options = webdriver.ChromeOptions()
chrome_options.add_argument('--ignore-ssl-errors')
chrome_options.add_argument('--ignore-certificate-errors-spki-list')
chrome_options.add_argument('--start-maximized')


capabilities = DesiredCapabilities().CHROME
capabilities["pageLoadStrategy"] = "none"

driver = webdriver.Chrome(desired_capabilities=capabilities, executable_path=r"C:\Users\supreme\Desktop\chromedriver.exe", seleniumwire_options=server, options=chrome_options)
```

**Comment by wkeeling** [comment]
Thanks. The issue is that you have overridden Selenium Wire's webdriver with Selenium's own webdriver. 

You should move this import to the bottom of the list:

```
from seleniumwire import webdriver
```

**Comment by kingAli110** [comment]
just did what u said, it worked but now i have another error
```
42
Traceback (most recent call last):
  File "C:\Users\supreme\Desktop\Account gen\main.py", line 88, in <module>
    driver.find_element_by_xpath('/html/body/div[3]/div/div[1]/div/div[1]/div/div[2]/div[2]/button').click()
  File "C:\Users\supreme\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Users\supreme\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\supreme\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\supreme\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementNotInteractableException: Message: element not interactable
  (Session info: chrome=93.0.4577.63)

>>> 127.0.0.1:51142: Traceback (most recent call last):
  File "C:\Users\supreme\AppData\Local\Programs\Python\Python39\lib\site-packages\seleniumwire\thirdparty\mitmproxy\net\tcp.py", line 94, in write
    r = self.o.write(v)
  File "C:\Users\supreme\AppData\Local\Programs\Python\Python39\lib\socket.py", line 722, in write
    return self._sock.send(b)
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\supreme\AppData\Local\Programs\Python\Python39\lib\site-packages\seleniumwire\thirdparty\mitmproxy\server\server.py", line 113, in handle
    root_layer()
  File "C:\Users\supreme\AppData\Local\Programs\Python\Python39\lib\site-packages\seleniumwire\thirdparty\mitmproxy\server\modes\http_proxy.py", line 23, in __call__
    layer()
  File "C:\Users\supreme\AppData\Local\Programs\Python\Python39\lib\site-packages\seleniumwire\thirdparty\mitmproxy\server\protocol\tls.py", line 285, in __call__
    layer()
  File "C:\Users\supreme\AppData\Local\Programs\Python\Python39\lib\site-packages\seleniumwire\thirdparty\mitmproxy\server\protocol\http1.py", line 100, in __call__
    layer()
  File "C:\Users\supreme\AppData\Local\Programs\Python\Python39\lib\site-packages\seleniumwire\thirdparty\mitmproxy\server\protocol\http.py", line 206, in __call__
    if not self._process_flow(flow):
  File "C:\Users\supreme\AppData\Local\Programs\Python\Python39\lib\site-packages\seleniumwire\thirdparty\mitmproxy\server\protocol\http.py", line 288, in _process_flow
    return self.handle_upstream_connect(f)
  File "C:\Users\supreme\AppData\Local\Programs\Python\Python39\lib\site-packages\seleniumwire\thirdparty\mitmproxy\server\protocol\http.py", line 251, in handle_upstream_connect
    self.send_response(f.response)
  File "C:\Users\supreme\AppData\Local\Programs\Python\Python39\lib\site-packages\seleniumwire\thirdparty\mitmproxy\server\protocol\http.py", line 54, in send_response
    self.send_response_body(response, [response.data.content])
  File "C:\Users\supreme\AppData\Local\Programs\Python\Python39\lib\site-packages\seleniumwire\thirdparty\mitmproxy\server\protocol\http1.py", line 72, in send_response_body
    self.client_conn.wfile.write(chunk)
  File "C:\Users\supreme\AppData\Local\Programs\Python\Python39\lib\site-packages\seleniumwire\thirdparty\mitmproxy\net\tcp.py", line 98, in write
    raise exceptions.TcpDisconnect(str(e))
seleniumwire.thirdparty.mitmproxy.exceptions.TcpDisconnect: [WinError 10053] An established connection was aborted by the software in your host machine
```

btw im creatin a bot for nike.com, so is it possible they could tell im usin proxies?

**Comment by wkeeling** [comment]
Yes it looks as though the remote server is cutting the connection. Do you get the same error if you omit the proxy?

**Comment by kingAli110** [comment]
no. i tried with selenium without proxies and it works, but when i switch to selenium wire and use proxies i get the error. do u think if i use undetected chromedriver it would help. dont knw much about it to be honest.

**Comment by wkeeling** [comment]
OK, thanks. I'm not sure that switching to undetetcted chromedriver will make any difference but you can try. It may also be worth downgrading to an earlier version of Selenium Wire - specifically 4.3.2 or earlier. Some proxy changes were made after this which may be causing the issue.

```
pip install selenium-wire==4.3.2
```

**Comment by kingAli110** [comment]
just switched to version 4.3.2 and it works. thank you so much.

**Comment by wkeeling** [comment]
I'll try to find the cause of this and get it fixed properly in the next release.
