### ISSUE TITLE
request body is emtpy

### ISSUE THREAD

**Issue by Culinator** [wkeeling/selenium-wire#39]
I tried to get an AJAX request and in principle it works. I see the request with header and the server's response, but without the data (status code is 200). I'm 100% sure that this Ajax query returns data, but I can't find it. 

There are also a lot of errors when loading the website, all of which don't occur with normal selenium.

I'm a bit overwhelmed myself at this point.

My code is relativ easy:

```
from seleniumwire import webdriver 


path = ""  # path to geckodriver
driver = webdriver.Firefox(executable_path=path)
driver.get('https://www.airbnb.de/rooms/28104490?guests=1&adults=1&check_in=2019-03-13&check_out=2019-03-18')

ajax_requests = [request for request in driver.requests if request.path.startswith("https://www.airbnb.de/api/v2/")]

```

**Comment by wkeeling** [comment]
@Culinator thanks for this.

It's possible that you're seeing an empty response for your AJAX request because the code is asking for the response body too soon, before the response has been fully captured. Is there a specific AJAX request that you're interested in with a specific URL? Or are you looking at any of the requests in the `ajax_requests` list? I'll see if I can reproduce this end.

Regarding the errors you're seeing when loading the website, can you post those and the tracebacks?

Thanks!

**Comment by Culinator** [comment]
@wkeeling thank your for your fast answer. 

Here are the error messages:
```
Loading 'screen' into random state - done
Loading 'screen' into random state - done
Loading 'screen' into random state - done
Loading 'screen' into random state - done
Loading 'screen' into random state - done
Loading 'screen' into random state - done
Loading 'screen' into random state - done
Loading 'screen' into random state - done
Loading 'screen' into random state - done
Loading 'screen' into random state - done
Loading 'screen' into random state - done
Loading 'screen' into random state - done
Loading 'screen' into random state - done
Loading 'screen' into random state - done
Loading 'screen' into random state - done
Loading 'screen' into random state -----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 63754)
Traceback (most recent call last):
  File "C:\Program Files\Python37\lib\socketserver.py", line 650, in process_request_thread
    self.finish_request(request, client_address)
  File "C:\Program Files\Python37\lib\socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "C:\Program Files\Python37\lib\site-packages\seleniumwire\proxy\proxy2.py", line 67, in __init__
    super().__init__(*args, **kwargs)
  File "C:\Program Files\Python37\lib\socketserver.py", line 720, in __init__
    self.handle()
  File "C:\Program Files\Python37\lib\http\server.py", line 428, in handle
    self.handle_one_request()
  File "C:\Program Files\Python37\lib\http\server.py", line 414, in handle_one_request
    method()
  File "C:\Program Files\Python37\lib\site-packages\seleniumwire\proxy\handler.py", line 127, in do_GET
    super().do_GET()
  File "C:\Program Files\Python37\lib\site-packages\seleniumwire\proxy\proxy2.py", line 226, in do_GET
    self.wfile.write(res_body)
  File "C:\Program Files\Python37\lib\socket.py", line 607, in write
    return self._sock.send(b)
  File "C:\Program Files\Python37\lib\ssl.py", line 984, in send
    return self._sslobj.write(data)
ConnectionAbortedError: [WinError 10053] Eine bestehende Verbindung wurde softwaregesteuert
durch den Hostcomputer abgebrochen
----------------------------------------
 done

````
This happens more than one time.

I do not think i have to wait longer, because on the website i see the results of the AJAX requests so its finish with loading. (I tested in debug mode)

At the moment i just testing so no there is no specific request which interest me. I just filterd out the requests to the API. For testing you can look at https://www.airbnb.de/api/v2/calendar_months... If you just copy the path and type it in your browser it works just fine.

Thanks to you!

**Comment by wkeeling** [comment]
@Culinator Thank you for the extra information and the traceback.

Interestingly the traceback seems to indicate that there is a problem writing the response body back over the socket to the client (browser). That must be the reason why the response bodies are not getting captured.

I notice you're running on Windows. I'll attempt to reproduce and report back here.

**Comment by elamperti** [comment]
Hi, is there any update on this? I started using the library recently and stumbled upon a similar problem (Linux here). A \[JSON\] *response* body appears empty, but from the browser's network inspector I can see it is not.

    >>> type(myrequest.response.body)
    <class 'NoneType'>

**Comment by wkeeling** [comment]
Thanks @elamperti . I have some more time coming up and I intend to look at this then. Interesting to see that it's also happening on Linux.

I'll let you know once I have an update.

**Comment by wkeeling** [comment]
@elamperti - do you have an example URL that exhibits this issue?

**Comment by elamperti** [comment]
@wkeeling I was working with a home banking site from my country, I'm afraid you won't be able to use it :disappointed: Sorry!

**Comment by wkeeling** [comment]
@elamperti - no problem, I've discovered the issue and I'm in the process of fixing.

**Comment by wkeeling** [comment]
@Culinator it seems the errors you're seeing when loading the site are unrelated to this issue. I will raise a separate issue to address those.

**Comment by Culinator** [comment]
Hey @wkeeling it seems the error still occures, but i cant find your new raised issue :)

**Comment by wkeeling** [comment]
Hi @Culinator , are we talking about the "Loading screen into random state" message, as you're right - I seem to have overlooked raising an issue! However, this has subsequently been raised by somebody else - see #52 and I intend to do a little digging to find the root cause. In the meantime, if you have any other insights into it, please share them here.
