### ISSUE TITLE
AttributeError: module 'lib' has no attribute 'SSL_CTX_get0_param'

### ISSUE THREAD

**Issue by sumthej** [wkeeling/selenium-wire#397]
Unable to load the web page using seleniumwire, i am observing this error in the browser.
```
This page isn't working
xxx.xyz didn't send any data.
ERR_EMPTY_RESPONSE
```
When i replace **seleniumwire** with **selenium** while initializing the webdriver, issue is no longer observed.
Seleniumwire was working fine and the below mentioned error started occurring couple of days ago.

Seleniumwire version: 4.4.0
Python 3.9
MacOS Big Sur

`ERROR:seleniumwire.server:127.0.0.1:61095: Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/seleniumwire/thirdparty/mitmproxy/server/server.py", line 113, in handle
    root_layer()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/seleniumwire/thirdparty/mitmproxy/server/modes/http_proxy.py", line 9, in __call__
    layer()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/seleniumwire/thirdparty/mitmproxy/server/protocol/tls.py", line 285, in __call__
    layer()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/seleniumwire/thirdparty/mitmproxy/server/protocol/http1.py", line 100, in __call__
    layer()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/seleniumwire/thirdparty/mitmproxy/server/protocol/http.py", line 206, in __call__
    if not self._process_flow(flow):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/seleniumwire/thirdparty/mitmproxy/server/protocol/http.py", line 285, in _process_flow
    return self.handle_regular_connect(f)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/seleniumwire/thirdparty/mitmproxy/server/protocol/http.py", line 224, in handle_regular_connect
    layer()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/seleniumwire/thirdparty/mitmproxy/server/protocol/tls.py", line 278, in __call__
    self._establish_tls_with_client_and_server()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/seleniumwire/thirdparty/mitmproxy/server/protocol/tls.py", line 358, in _establish_tls_with_client_and_server
    self._establish_tls_with_server()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/seleniumwire/thirdparty/mitmproxy/server/protocol/tls.py", line 445, in _establish_tls_with_server
    self.server_conn.establish_tls(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/seleniumwire/thirdparty/mitmproxy/connections.py", line 295, in establish_tls
    self.convert_to_tls(cert=client_cert, sni=sni, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/seleniumwire/thirdparty/mitmproxy/net/tcp.py", line 382, in convert_to_tls
    context = tls.create_client_context(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/seleniumwire/thirdparty/mitmproxy/net/tls.py", line 285, in create_client_context
    param = SSL._lib.SSL_CTX_get0_param(context._context)
AttributeError: module 'lib' has no attribute 'SSL_CTX_get0_param'`

**Comment by wkeeling** [comment]
Thanks for the update. The error looks like it's related to OpenSSL. If this error has suddenly started happening, perhaps the version of OpenSSL may have changed in your environment - e.g. after an automated OS update.

Can you let me know what you get from the following commands:
```
openssl version
```
and:
```
pip show PyOpenSSL
```

**Comment by sumthej** [comment]
sorry for the late response, please find the output of the commands.

**openssl version**
```
OpenSSL 1.1.1l  24 Aug 2021
```

**pip show PyOpenSSL**
```
Name: pyOpenSSL
Version: 20.0.1
Summary: Python wrapper module around the OpenSSL library
Home-page: https://pyopenssl.org/
Author: The pyOpenSSL developers
Author-email: cryptography-dev@python.org
License: Apache License, Version 2.0
Location: /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages
Requires: six, cryptography
Required-by: selenium-wire
```

**Comment by wkeeling** [comment]
Thanks. The version of OpenSSL you're running is less than 1 month old, so I wonder whether this has recently been upgraded and could be causing the problem (your PyOpenSSL is fine).

The version of OpenSSL I'm running is:

```
$ openssl version
OpenSSL 1.1.1  11 Sep 2018
```
Could you try installing version `1.1.1` with:
```
brew install openssl@1.1.1
```

**Comment by sumthej** [comment]
Thank you, tried installing Openssl but I still observe the same issue with SeleniumWire.
I will try to reinstall Openssl and see if that works.

**Comment by ffo12** [comment]
Has anyone found a fix? JUST importing Seleniumwire stops pages from loading.

**Comment by wkeeling** [comment]
@ffo12 I assume you're also getting this error:
```
AttributeError: module 'lib' has no attribute 'SSL_CTX_get0_param'
```

**Comment by dsu** [comment]
Was this issue fixed? I still have similar error on Linux.

**Comment by mibxu** [comment]
I can't install openssl@1.1.1

`
$ openssl version
OpenSSL 1.1.1i  8 Dec 2020

$ brew install openssl@1.1.1
Running `brew update --preinstall`...
Warning: No available formula with the name "openssl@1.1.1". Did you mean openssl@1.1?
==> Searching for similarly named formulae...
This similarly named formula was found:
openssl@1.1 ✔
To install it, run:
  brew install openssl@1.1 ✔
==> Searching for a previously deleted formula (in the last month)...
Error: No previously deleted formula found.
==> Searching taps on GitHub...
Error: No formulae found in taps.
`

**Comment by mibxu** [comment]
I can't install openssl@1.1.1

`
$ openssl version
OpenSSL 1.1.1i  8 Dec 2020

$ brew install openssl@1.1.1
Running "brew update --preinstall"...
Warning: No available formula with the name "openssl@1.1.1". Did you mean openssl@1.1?
==> Searching for similarly named formulae...
This similarly named formula was found:
openssl@1.1 ✔
To install it, run:
  brew install openssl@1.1 ✔
==> Searching for a previously deleted formula (in the last month)...
Error: No previously deleted formula found.
==> Searching taps on GitHub...
Error: No formulae found in taps.
`

**Comment by wkeeling** [comment]
@ma-marco-mariotto I have those exact versions of both `pyopenssl` and `openssl` and everything works ok. What version of `cffi` are you running?

**Comment by ma-marco-mariotto** [comment]
> @ma-marco-mariotto I have those exact versions of both `pyopenssl` and `openssl` and everything works ok. What version of `cffi` are you running?

1.15.1

**Comment by anshul-bst** [comment]
I have tried with
selenium-wire==4.6.2
pyopenssl==22.0.0
and its working
