### ISSUE TITLE
permissions issue

### ISSUE THREAD

**Issue by felipesantos989** [wkeeling/selenium-wire#411]
Selenium is normal
Selenium-wire i'm having permission issues, already tried a lot of stuff but no luck.

What i'm doing: I'm acessing a php file through web http://localhost/something.php this file executes a python selenium-wire-script.py file
and the result is below:

```
Traceback (most recent call last):
  | File "/home/file.py", line 11, in <module>
  | driver = webdriver.Chrome(PATH,chrome_options=chrome_options)
  | File "/usr/local/lib/python3.6/dist-packages/seleniumwire/webdriver/browser.py", line 69, in __init__
  | options=seleniumwire_options
  | File "/usr/local/lib/python3.6/dist-packages/seleniumwire/proxy/backend.py", line 45, in create
  | proxy = ProxyHTTPServer(addr, port, capture_request_handler, options=options)
  | File "/usr/local/lib/python3.6/dist-packages/seleniumwire/proxy/server.py", line 49, in __init__
  | base_dir=self.options.pop('request_storage_base_dir', None)
  | File "/usr/local/lib/python3.6/dist-packages/seleniumwire/proxy/storage.py", line 41, in __init__
  | os.makedirs(self._storage_dir)
  | File "/usr/lib/python3.6/os.py", line 210, in makedirs
  | makedirs(head, mode, exist_ok)
  | File "/usr/lib/python3.6/os.py", line 220, in makedirs
  | mkdir(name, mode)
  | PermissionError: [Errno 13] Permission denied: '/var/www/.seleniumwire'
```

**Comment by wkeeling** [comment]
Thanks for raising this.

It looks as though Selenium Wire is configured to use `/var/www/` for request storage, but that directory isn't accessible when Selenium Wire runs.

Try changing Selenium Wire's storage directory to a writeable location:
```python
options = {
    'request_storage_base_dir': '/tmp'
}
driver = webdriver.Chrome(seleniumwire_options=options)
```

**Comment by felipesantos989** [comment]
@wkeeling thank you so much for your help!
it worked perfectly!
