### ISSUE TITLE
selenium wire edit post json request error

### ISSUE THREAD

**Issue by felipesantos989** [wkeeling/selenium-wire#413]
**CODE:**
```
from seleniumwire import webdriver
import json

# chrome driver
PATH = "C:/Users/Unknown/Documents/Selenium/chromedriver.exe"
driver = webdriver.Chrome(PATH)


def interceptor(request):
    if request.method == 'POST' and request.headers['Content-Type'] == 'application/json':
        # The body is in bytes so convert to a string
        body = request.body.decode('utf-8')
        # Load the JSON
        data = json.loads(body)
        # Add a new property
        data['foo'] = 'bar'
        # Set the JSON back on the request
        request.body = json.dumps(data).encode('utf-8')
        # Update the content length
        del request.headers['Content-Length']
        request.headers['Content-Length'] = str(len(request.body))

driver.request_interceptor = interceptor

# navigate to website
driver.get('http://www.example.com/')
```

**ERROR:**
```
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Try the new cross-platform PowerShell https://aka.ms/pscore6

PS C:\Users\Unknown> & C:/Users/Unknown/AppData/Local/Programs/Python/Python39/python.exe c:/Users/Unknown/Documents/Selenium/teste.py

DevTools listening on ws://127.0.0.1:63596/devtools/browser/5e17f3da-14ea-4c0f-999d-4d8100c8b8da
Error handling request
Traceback (most recent call last):
  File "C:\Users\Unknown\AppData\Local\Programs\Python\Python39\lib\site-packages\seleniumwire\handler.py", line 42, in request
    self.proxy.request_interceptor(request)
  File "c:\Users\Unknown\Documents\Selenium\teste.py", line 14, in interceptor
    data = json.loads(body)
  File "C:\Users\Unknown\AppData\Local\Programs\Python\Python39\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\Unknown\AppData\Local\Programs\Python\Python39\lib\json\decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 26 (char 25)

Error handling request
Traceback (most recent call last):
  File "C:\Users\Unknown\AppData\Local\Programs\Python\Python39\lib\site-packages\seleniumwire\handler.py", line 42, in request
    self.proxy.request_interceptor(request)
  File "c:\Users\Unknown\Documents\Selenium\teste.py", line 14, in interceptor
    data = json.loads(body)
  File "C:\Users\Unknown\AppData\Local\Programs\Python\Python39\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\Unknown\AppData\Local\Programs\Python\Python39\lib\json\decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 6 (char 5)

Error handling request
Traceback (most recent call last):
  File "C:\Users\Unknown\AppData\Local\Programs\Python\Python39\lib\site-packages\seleniumwire\handler.py", line 42, in request
    self.proxy.request_interceptor(request)
  File "c:\Users\Unknown\Documents\Selenium\teste.py", line 14, in interceptor
    data = json.loads(body)
  File "C:\Users\Unknown\AppData\Local\Programs\Python\Python39\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\Unknown\AppData\Local\Programs\Python\Python39\lib\json\decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 24 (char 23)

Error handling request
Traceback (most recent call last):
  File "C:\Users\Unknown\AppData\Local\Programs\Python\Python39\lib\site-packages\seleniumwire\handler.py", line 42, in request
    self.proxy.request_interceptor(request)
  File "c:\Users\Unknown\Documents\Selenium\teste.py", line 14, in interceptor
    data = json.loads(body)
  File "C:\Users\Unknown\AppData\Local\Programs\Python\Python39\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\Unknown\AppData\Local\Programs\Python\Python39\lib\json\decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 6 (char 5)

Error handling request
Traceback (most recent call last):
  File "C:\Users\Unknown\AppData\Local\Programs\Python\Python39\lib\site-packages\seleniumwire\handler.py", line 42, in request
    self.proxy.request_interceptor(request)
  File "c:\Users\Unknown\Documents\Selenium\teste.py", line 14, in interceptor
    data = json.loads(body)
  File "C:\Users\Unknown\AppData\Local\Programs\Python\Python39\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\Unknown\AppData\Local\Programs\Python\Python39\lib\json\decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 16 (char 15)

Error handling request
Traceback (most recent call last):
  File "C:\Users\Unknown\AppData\Local\Programs\Python\Python39\lib\site-packages\seleniumwire\handler.py", line 42, in request
    self.proxy.request_interceptor(request)
  File "c:\Users\Unknown\Documents\Selenium\teste.py", line 14, in interceptor
    data = json.loads(body)
  File "C:\Users\Unknown\AppData\Local\Programs\Python\Python39\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\Unknown\AppData\Local\Programs\Python\Python39\lib\json\decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 6 (char 5)

Error handling request
Traceback (most recent call last):
  File "C:\Users\Unknown\AppData\Local\Programs\Python\Python39\lib\site-packages\seleniumwire\handler.py", line 42, in request
    self.proxy.request_interceptor(request)
  File "c:\Users\Unknown\Documents\Selenium\teste.py", line 14, in interceptor
    data = json.loads(body)
  File "C:\Users\Unknown\AppData\Local\Programs\Python\Python39\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\Unknown\AppData\Local\Programs\Python\Python39\lib\json\decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 6 (char 5)

PS C:\Users\Unknown> 
```

**Comment by wkeeling** [comment]
Thanks for this.

Can you print the contents of the decoded body before you try to load it as JSON? For example:

```python
def interceptor(request):
    if request.method == 'POST' and request.headers['Content-Type'] == 'application/json':
        # The body is in bytes so convert to a string
        body = request.body.decode('utf-8')
        print(body)  # <------------------------------- print out the body
        # Load the JSON
        data = json.loads(body)
        # Add a new property
        data['foo'] = 'bar'
        # Set the JSON back on the request
        request.body = json.dumps(data).encode('utf-8')
        # Update the content length
        del request.headers['Content-Length']
        request.headers['Content-Length'] = str(len(request.body))
```
... and let me know what it prints?

**Comment by felipesantos989** [comment]
```
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Try the new cross-platform PowerShell https://aka.ms/pscore6

PS C:\Users\Unknown> & C:/Users/Unknown/AppData/Local/Programs/Python/Python39/python.exe c:/Users/Unknown/Documents/Selenium/teste.py

DevTools listening on ws://127.0.0.1:58790/devtools/browser/e908e80f-720f-4dbb-a87f-031d2cfc6c0f
51744d6d6b4771366b6b457a3137784271364a6e7156486679586750786f52746547444543336739654577686550412f59707634445433356166514168524d46486e414848762f6a6e6e686a756770676175534a716f5a72447a2b445674362b6b455a57534b33316c446b484e6f514b667a2f38362b6f436437514441485455322b6353392f3975717a4a555847625136414f44582f69786c4f6e57354f5548316c2b7a5a7857784f59327864546d35332b6661586e326b74394f3274416153703877476856667042354e4e566a674a316136496a374f426c7149366f4b593369656b5a324e76796b6467563731334c6a6d3065706f516f3069584874616b70625547626f37455432705662574574555739614f7a32367545722f395a656e744d61426458345a52664c3873466e364452736f7758364443314676434161634a57797942324877335036547872756e3444777177726a466f51712b766f4b756c594658367967424e554a3574533158376b4e486a68322f416c706a53574f7667486b7a4a2f6a57454866453d
Error handling request
Traceback (most recent call last):
  File "C:\Users\Unknown\AppData\Local\Programs\Python\Python39\lib\site-packages\seleniumwire\handler.py", line 42, in request
    self.proxy.request_interceptor(request)
  File "c:\Users\Unknown\Documents\Selenium\teste.py", line 15, in interceptor
    data = json.loads(body)
  File "C:\Users\Unknown\AppData\Local\Programs\Python\Python39\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\Unknown\AppData\Local\Programs\Python\Python39\lib\json\decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 6 (char 5)

68574871757564536e5979706d524c397a4a744e4c654668353868795461753250504f585069536e5567543430353864424a4e626c5767777a35596564564c797941427750715656355a376e49766a2b656a62517a445058764547726f6d65707955567553447154554177434a48634f3768374578676248432b586a65423032382f4c55364a504f456a3649346370725047797a7a54476758562b475558792f464e654c665a7a6e697448596b4e6b634b586c674a7458675879726a49466848527a66306b4a2f76514b614b5535595451364c714b55316a4342536c563363336c7766544c766b58364e504d4a72554753664c6a6167356474526c7173306e326e32356c6a434b63352b514752326d385237447235536c505942736730642b4f6577314e304c4962794b6437324e52637667467367766265334878454f734b7736455666784f6d716771434e464f667932772b5873414d714942466a4553387169556742347a623175532b5333786776785a6e7044486c72502b5458437267743655415278754b4b2f51383d
Error handling request
Traceback (most recent call last):
  File "C:\Users\Unknown\AppData\Local\Programs\Python\Python39\lib\site-packages\seleniumwire\handler.py", line 42, in request
    self.proxy.request_interceptor(request)
  File "c:\Users\Unknown\Documents\Selenium\teste.py", line 15, in interceptor
    data = json.loads(body)
  File "C:\Users\Unknown\AppData\Local\Programs\Python\Python39\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\Unknown\AppData\Local\Programs\Python\Python39\lib\json\decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 26 (char 25)

51744d6d6b4771366b6b457a3137784271364a6e7156486679586750786f52746547444543336739654577686550412f59707634445433356166514168524d46486e414848762f6a6e6e686a756770676175534a716f5a72447a2b445674362b6b455a57534b33316c446b484e6f514b667a2f38362b6f436437514441485455322b6353392f3975717a4a555847625136414f44582f69786c4f6e57354f5548316c2b7a5a7857784f59327864546d35332b6661586e326b74394f3274416153703877476856667042354e4e566a674a316136496a374f426c7149366f4b593369656b5a324e76796b6467563731334c6a6d3065706f516f3069584874616b70625547626f37455432705662574574555739614f7a32367545722f395a656e744d61426458345a52664c3873466e364452736f7758364443314676434161634a57797942324877335036547872756e34447771777269756a5247434568694d44
Error handling request
Traceback (most recent call last):
  File "C:\Users\Unknown\AppData\Local\Programs\Python\Python39\lib\site-packages\seleniumwire\handler.py", line 42, in request
    self.proxy.request_interceptor(request)
  File "c:\Users\Unknown\Documents\Selenium\teste.py", line 15, in interceptor
    data = json.loads(body)
  File "C:\Users\Unknown\AppData\Local\Programs\Python\Python39\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\Unknown\AppData\Local\Programs\Python\Python39\lib\json\decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 6 (char 5)

62443745675555554348797a675a61694f71436d4e374c654b6c732b636a624e794b417158794744635264575a316e6c435761316d314a586d2f795239774b4450306b4b666a6c4a66486a6d4c3735484e654e5063745a6c617257346a6f773852364b664338586f67746b473361764a334769586e335265397335317935712f344d317a342b34386e704f734a414c2f2f7a6b4a3043584174694b6c414e773545355a4d667a75373575465a62544f796c4f2f302f2b444e632b5075504a36546a7a55636b52556c5567566465536e3468615361326148615354332b556e4d35423552582f7033766265727262516c6d6e69304e4538663131633632455a4151623843576d4e4a59362b424e4e50453578782b495177613468694f6c3449386d574a4b2b706a4d7a643851366851596957774f30614e496145562f413269786a384d3573574d5a586c5343617765744f6c3948706a3571444565773842487a49
Error handling request
Traceback (most recent call last):
  File "C:\Users\Unknown\AppData\Local\Programs\Python\Python39\lib\site-packages\seleniumwire\handler.py", line 42, in request
    self.proxy.request_interceptor(request)
  File "c:\Users\Unknown\Documents\Selenium\teste.py", line 15, in interceptor
    data = json.loads(body)
  File "C:\Users\Unknown\AppData\Local\Programs\Python\Python39\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\Unknown\AppData\Local\Programs\Python\Python39\lib\json\decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 24 (char 23)

7761746e6630754c756748626f4f54435679505346726b7072357736654844722b31316153794c565a674e526e52357535586e513032736948682b39563437732f6d46432f6446677a53314258677a39414750757a56367642674d2b70397a4f3667366f3255694a3968416c514e4a415447303943693069615035617a51344b3758636c6e51717a4a576c4e5744566b397a3554386c6464664c524666344832467147634766495332714b70664551526463725a497771567139717a434e4a54696d68737a7374395152316b4e7267434a57767770757342734f7352623743455a6c436a4849554668754f346977556e31342b656c5849644865533952426f305652323149516d4c2b4d2b37535552625075716b756a476758562b475558792f424b734a2b33456850435072764e67613963474f3969326966544672617461582b556f64394c59644454354e59776755705664334e2b5976766b633134303979316d56717462694f6a44777a786b644e4a6b68796d7975782b657641554b4d69376877713234377141486c74376265755431706f546e412f67347477526b7a3176746561337331736c7439782b794e4145696542445772793370344457594c6d3332334859754a455970306f6f444f4750354f7a486b51466635776834356d57626a357073566e4d6e524668484f334671614642786f316f306a317638476c4b716142392f6463724877396350692f4d7a4c5742416f536d486b494f6646576c
Error handling request
Traceback (most recent call last):
  File "C:\Users\Unknown\AppData\Local\Programs\Python\Python39\lib\site-packages\seleniumwire\handler.py", line 42, in request
    self.proxy.request_interceptor(request)
  File "c:\Users\Unknown\Documents\Selenium\teste.py", line 15, in interceptor
    data = json.loads(body)
  File "C:\Users\Unknown\AppData\Local\Programs\Python\Python39\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\Unknown\AppData\Local\Programs\Python\Python39\lib\json\decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 16 (char 15)

[18672:17024:0928/233024.918:ERROR:ssl_client_socket_impl.cc(981)] handshake failed; returned -1, SSL error code 1, net_error -101
PS C:\Users\Unknown>
```

**Comment by wkeeling** [comment]
Yes if the request body is encoded (or encrypted) which it seems to be, then you'll need to decode (or decrypt) it first before you can use `json.loads()`. Selenium Wire will automatically decrypt at the HTTPS layer but if the request body has been encrypted separately - which appears to be the case here - then you'll need to decrypt it yourself before you can manipulate it.

**Comment by felipesantos989** [comment]
But is there any way to update the json without decrypting it?
this encrypted stuff is a not logged in a session: ```51744d6d6b4771366b6b457a3137784271364a6e715648...```

so what i did: i logged in manually, and copied the logged in session ```79776b364c726e734d447a2b71494f33424c58...```
and now what i'm trying to do is to set this json everytime i hit play on the script, so i don't need to login using credentials everytime and solving the captcha.

so i need to post it like that, without decrypting or encrypting it.
i don't need to see what's encrypted, i just need to post it like that.
i've tried doing this using Charles before, and it worked fine, so i know it will work.

**Comment by felipesantos989** [comment]
Thank you so much for your help, i was able to solve it using this code:

```
def interceptor(request):
    if request.method == 'POST' and request.headers['Content-Type'] == 'application/json' and request.url == 'http://www.example.com/api/getAuthInfo':
        # The body is in bytes so convert to a string
        body = request.body.decode('utf-8')
        print(request.url)
        print(body)  # <------------------------------- print out the body
        # Set the JSON back on the request
        request.body = "79776b364c726e734d447a2b71494f33424c58..."

driver.request_interceptor = interceptor
```
