### ISSUE TITLE
Batch execusion: filedescriptor out of range in select

### ISSUE THREAD

**Issue by jonfrs** [wkeeling/selenium-wire#434]
When I run a loop for collect in different pages, a specific request, after ± 200 loads show this error:

```
Exception in thread ServerThread (('127.0.0.1', 41075)):
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/home/jonathan/Projetos/PJ1/venv/lib/python3.7/site-packages/seleniumwire/thirdparty/mitmproxy/master.py", line 36, in run
    self.server.serve_forever()
  File "/home/jonathan/Projetos/PJ1/venv/lib/python3.7/site-packages/seleniumwire/thirdparty/mitmproxy/net/tcp.py", line 650, in serve_forever
    r, w_, e_ = select.select([self.socket], [], [], poll_interval)
ValueError: filedescriptor out of range in select()
```

I need restart wsl or, in jupyter, reset the session to continue.

**Comment by wkeeling** [comment]
Thanks for raising this and sorry for the delay in replying.

It looks as though you've hit the maximum open file descriptor limit on your machine. When you start each loop, are you creating a new webdriver instance - i.e. are you calling `webdriver.Chrome()` at the beginning of each loop? If so, are you closing the browser with `webdriver.quit()` at the end of each loop? The `quit()` method will ensure that the Selenium Wire server is properly shutdown behind the scenes.

**Comment by SeriyVol4ishe** [comment]
@wkeeling even if I call .quit(), after a day stable working this problem occurs.

**Comment by SeriyVol4ishe** [comment]
hm, may be it's not selenium-wire problem.

**Comment by SeriyVol4ishe** [comment]
https://github.com/mitmproxy/mitmproxy/issues/4514

**Comment by wkeeling** [comment]
Selenium Wire still uses the old mitmproxy core, so this will likely continue to affect Selenium Wire (there's no plans to upgrade the proxy core at the present time). I'll see if there's anything we can do.

**Comment by leetomlee123** [comment]
i got this issue ,latest version fixed ?

**Comment by awais-tahir-qbatch** [comment]
I am experiencing the same issue. Do you have a solution for this?
