### ISSUE TITLE
[4.5.4] ModuleNotFoundError: No module named 'packaging'

### ISSUE THREAD

**Issue by alexandrenicol** [wkeeling/selenium-wire#438]
## Issue
When trying to import seleniumwire (version 4.5.4) in a python script, an error is thrown.

## Expected behaviour
Importing seleniumwire doesn't throw any error.

## Actual behaviour
Importing seleniumwire throw the following error:

```
ModuleNotFoundError: No module named 'packaging'
```

### Code used

```python
from seleniumwire import webdriver
```

### Dependencies:
(Poetry)
```
[tool.poetry.dependencies]
python = "^3.9"
selenium = "^4.0.0"
PyVirtualDisplay = "^2.2"
awslambdaric = "^2.0.0"
selenium-wire = "4.5.4"
boto3 = "^1.19.10"
python-dotenv = "^0.19.1"
```

### Traceback

```
[root - INFO - 2021-11-04 11:28:16,158] START RequestId: 64f5ad8e-adf7-4e25-a389-b3b358158167 Version: 
Process Process-1:
Traceback (most recent call last):
  File "/home/raoul/.pyenv/versions/3.9.6/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/raoul/.pyenv/versions/3.9.6/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/raoul/.cache/pypoetry/virtualenvs/policy-diff-browser-aMsmDRuN-py3.9/lib/python3.9/site-packages/lambda_local/main.py", line 171, in execute_in_process
    loader.load()
  File "/home/raoul/.cache/pypoetry/virtualenvs/policy-diff-browser-aMsmDRuN-py3.9/lib/python3.9/site-packages/lambda_local/main.py", line 59, in load
    self.func = load_source(
  File "/home/raoul/.cache/pypoetry/virtualenvs/policy-diff-browser-aMsmDRuN-py3.9/lib/python3.9/site-packages/lambda_local/main.py", line 136, in load_source
    spec.loader.exec_module(mod)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "app.py", line 2, in <module>
    from seleniumwire import webdriver
  File "/home/raoul/.cache/pypoetry/virtualenvs/policy-diff-browser-aMsmDRuN-py3.9/lib/python3.9/site-packages/seleniumwire/webdriver.py", line 4, in <module>
    from packaging import version
ModuleNotFoundError: No module named 'packaging'
```

Thanks!

**Comment by alexandrenicol** [comment]
Just adding a comment to say that downgrading seleniumwire to 4.5.3 solves the issue.

**Comment by wkeeling** [comment]
Many thanks for the bug report. I think the `packaging` module normally comes as part of `pip` itself, but may not be present on all systems depending upon how Python/pip was installed. [This SO](https://stackoverflow.com/questions/42222096/no-module-named-packaging) gives some more info. I'll look at using a fallback option when `packaging` isn't present.

**Comment by alexandrenicol** [comment]
Thanks for the swift reply.

That makes sense. I'm using pyenv+poetry (with Python 3.9.6 & pip 21.1.3) on WSL, so it might be something to do with that. 

Thanks for looking into it!

**Comment by tailaiw** [comment]
Same issue here, using inside a docker container with `python:3.9-slim` as base image.

**Comment by wkeeling** [comment]
Version 4.5.5 should now fix this.
