### ISSUE TITLE
Missing dependency on cffi

### ISSUE THREAD

**Issue by nyuszika7h** [wkeeling/selenium-wire#447]
When I install selenium-wire and try to run a script using it, I get the following error:

```pytb
Traceback (most recent call last):                                               
[snip]
  File "/home/nyuszika7h/test/test.py", line 16, in <module>
    from seleniumwire import webdriver
  File "/home/nyuszika7h/test/.venv/lib/python3.10/site-packages/seleniumwire/webdriver.py", line 22, in <module>
    from seleniumwire import backend
  File "/home/nyuszika7h/test/.venv/lib/python3.10/site-packages/seleniumwire/backend.py", line 4, in <module>
    from seleniumwire.server import MitmProxy
  File "/home/nyuszika7h/test/.venv/lib/python3.10/site-packages/seleniumwire/server.py", line 5, in <module>
    from seleniumwire.handler import InterceptRequestHandler
  File "/home/nyuszika7h/test/.venv/lib/python3.10/site-packages/seleniumwire/handler.py", line 5, in <module>
    from seleniumwire import har
  File "/home/nyuszika7h/test/.venv/lib/python3.10/site-packages/seleniumwire/har.py", line 11, in <module>
    from seleniumwire.thirdparty.mitmproxy import connections
  File "/home/nyuszika7h/test/.venv/lib/python3.10/site-packages/seleniumwire/thirdparty/mitmproxy/connections.py", line 9, in <module>
    from seleniumwire.thirdparty.mitmproxy import certs, exceptions, stateobject
  File "/home/nyuszika7h/test/.venv/lib/python3.10/site-packages/seleniumwire/thirdparty/mitmproxy/certs.py", line 10, in <module>
    import OpenSSL
  File "/home/nyuszika7h/test/.venv/lib/python3.10/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import crypto, SSL
  File "/home/nyuszika7h/test/.venv/lib/python3.10/site-packages/OpenSSL/crypto.py", line 17, in <module>
    from OpenSSL._util import (
  File "/home/nyuszika7h/test/.venv/lib/python3.10/site-packages/OpenSSL/_util.py", line 6, in <module>
    from cryptography.hazmat.bindings.openssl.binding import Binding
  File "/home/nyuszika7h/test/.venv/lib/python3.10/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 14, in <module>
    from cryptography.hazmat.bindings._openssl import ffi, lib
ModuleNotFoundError: No module named '_cffi_backend'
```

`pip install cffi` solves the issue. It should probably be added as a dependency.

**Comment by wkeeling** [comment]
Thank you for raising this.

This is odd as the `cryptography` module should [automatically bring in `cffi`](https://github.com/pyca/cryptography/blob/9177dd203b9183db5986569ddef992de98dea633/setup.cfg#L49). The `cryptography` module is brought in by PyOpenSSL which itself is brought in by Selenium Wire. Something must have gone wrong with dependency resolution somewhere.

I see you're running on Python 3.10 so I'll look at reproducing and see whether it's a general problem. Thanks again.

**Comment by nyuszika7h** [comment]
I'm also using Poetry in case it makes a difference.

**Comment by nyuszika7h** [comment]
Indeed, it looks like this may be an issue with Poetry. If I do `pip install selenium-wire`, cffi gets pulled in correctly.

**Comment by wkeeling** [comment]
Thanks for confirming. I'll close this for now.
