### ISSUE TITLE
Permission Issue, script only work in /root directory

### ISSUE THREAD

**Issue by felipesantos989** [wkeeling/selenium-wire#478]
**Code:**

```
from seleniumwire import webdriver # Capture Network Activity (pip install selenium-wire)
from webdriver_manager.chrome import ChromeDriverManager # ChromeDriver Manager
from selenium.webdriver.chrome.service import Service # ChromeDriver Manager
from selenium.webdriver.chrome.options import Options # Options()

# options
options = Options()
options.add_argument('--headless')
options.add_argument('--no-sandbox')
options.add_argument('--disable-dev-shm-usage')

# chrome driver
driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()), options=options)


# navigate to website
driver.get('http://www.google.com/')
print("Sucess!")
```

**I also have tried adding this to the code:**

```
seleniumwire_options = {
    'request_storage_base_dir': '/tmp'
}

seleniumwire_options=seleniumwire_options
```

**Result (not in root directory):**

```
root@server:~# python3 /root/selenium_scripts/teste.py
Traceback (most recent call last):
  File "/root/selenium_scripts/teste.py", line 1, in <module>
    from seleniumwire import webdriver # Capture Network Activity (pip install selenium-wire)
  File "/usr/local/lib/python3.7/dist-packages/seleniumwire/webdriver.py", line 22, in <module>
    from seleniumwire import backend
  File "/usr/local/lib/python3.7/dist-packages/seleniumwire/backend.py", line 4, in <module>
    from seleniumwire.server import MitmProxy
  File "/usr/local/lib/python3.7/dist-packages/seleniumwire/server.py", line 10, in <module>
    from seleniumwire.thirdparty.mitmproxy.server import ProxyConfig, ProxyServer
  File "/usr/local/lib/python3.7/dist-packages/seleniumwire/thirdparty/mitmproxy/server/__init__.py", line 2, in <module>
    from .root_context import RootContext
  File "/usr/local/lib/python3.7/dist-packages/seleniumwire/thirdparty/mitmproxy/server/root_context.py", line 3, in <module>
    from seleniumwire.thirdparty.mitmproxy.server import modes, protocol
  File "/usr/local/lib/python3.7/dist-packages/seleniumwire/thirdparty/mitmproxy/server/modes/__init__.py", line 1, in <module>
    from .http_proxy import HttpProxy, HttpUpstreamProxy
  File "/usr/local/lib/python3.7/dist-packages/seleniumwire/thirdparty/mitmproxy/server/modes/http_proxy.py", line 1, in <module>
    from seleniumwire.thirdparty.mitmproxy.server import protocol
  File "/usr/local/lib/python3.7/dist-packages/seleniumwire/thirdparty/mitmproxy/server/protocol/__init__.py", line 33, in <module>
    from .http import HttpLayer, UpstreamConnectLayer
  File "/usr/local/lib/python3.7/dist-packages/seleniumwire/thirdparty/mitmproxy/server/protocol/http.py", line 7, in <module>
    import h2.exceptions
  File "/root/selenium_scripts/h2.py", line 22, in <module>
    driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()), options=options)
AttributeError: module 'seleniumwire.webdriver' has no attribute 'Chrome'
```

**Result (in root directory):**

```
root@server:~# python3 /root/teste.py


====== WebDriver manager ======
Current google-chrome version is 96.0.4664
Get LATEST chromedriver version for 96.0.4664 google-chrome
Driver [/root/.wdm/drivers/chromedriver/linux64/96.0.4664.45/chromedriver] found in cache
Sucess!
```

**Comment by felipesantos989** [comment]
I found out that a file called ```h2.py``` is causing this bug, i renamed the file and everything went fine, 
but i don't understand why this happens, if i didn't link anything, if i rename the file back to same name, it continues to happen, do you know any way to fix this?

```
File "/root/selenium_scripts/h2.py", line 22, in <module>
    driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()), options=options)
```

**Comment by wkeeling** [comment]
I don't have a `h2.py` on my system so I'm not entirely sure why it's having this effect in your environment. I tried reproducing the issue with the code above but it seems to work fine for me (presumably because I don't have an `h2.py`). Here's the code I'm using and output (with logging enabled).

```python
import logging

from seleniumwire import webdriver
from webdriver_manager.chrome import ChromeDriverManager # ChromeDriver Manager
from selenium.webdriver.chrome.service import Service # ChromeDriver Manager
from selenium.webdriver.chrome.options import Options # Options()

logging.basicConfig(level=logging.INFO)

options = Options()
options.add_argument('--headless')
options.add_argument('--no-sandbox')
options.add_argument('--disable-dev-shm-usage')

# chrome driver
driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()), options=options)

# navigate to website
driver.get('http://www.google.com/')
print("Sucess!")
```

**Result**
```
====== WebDriver manager ======
INFO:WDM:

INFO:WDM:====== WebDriver manager ======
Current google-chrome version is 96.0.4664
Get LATEST chromedriver version for 96.0.4664 google-chrome
INFO:WDM:Current google-chrome version is 96.0.4664
INFO:WDM:Get LATEST chromedriver version for 96.0.4664 google-chrome
INFO:WDM:Driver [/home/will/.wdm/drivers/chromedriver/linux64/96.0.4664.45/chromedriver] found in cache
INFO:seleniumwire.storage:Using default request storage
INFO:seleniumwire.backend:Created proxy listening on 127.0.0.1:44941
Driver [/home/will/.wdm/drivers/chromedriver/linux64/96.0.4664.45/chromedriver] found in cache
INFO:seleniumwire.handler:Capturing request: http://www.google.com/
INFO:seleniumwire.handler:Capturing response: http://www.google.com/ 302 Found
INFO:seleniumwire.handler:Capturing request: https://www.google.com/?gws_rd=ssl
INFO:seleniumwire.handler:Capturing response: https://www.google.com/?gws_rd=ssl 200 
INFO:seleniumwire.handler:Capturing request: https://www.google.com/logos/doodles/2021/new-years-eve-2021-6753651837109170-6752733080595621-cst.gif
INFO:seleniumwire.handler:Capturing request: https://www.google.com/images/searchbox/desktop_searchbox_sprites318_hr.webp
INFO:seleniumwire.handler:Capturing request: https://www.google.com/gen_204?ei=xtjOYZuOLfW78gLT6ZPYCg&vet=10ahUKEwibifrZ5431AhX1nVwKHdP0BKsQhJAHCBY..s&gl=GB&pc=SEARCH_HOMEPAGE&isMobile=false
INFO:seleniumwire.handler:Capturing response: https://www.google.com/logos/doodles/2021/new-years-eve-2021-6753651837109170-6752733080595621-cst.gif 200 
INFO:seleniumwire.handler:Capturing response: https://www.google.com/images/searchbox/desktop_searchbox_sprites318_hr.webp 200 
INFO:seleniumwire.handler:Capturing request: https://fonts.gstatic.com/s/i/productlogos/googleg/v6/24px.svg
INFO:seleniumwire.handler:Capturing response: https://fonts.gstatic.com/s/i/productlogos/googleg/v6/24px.svg 200 
INFO:seleniumwire.handler:Capturing request: https://www.gstatic.com/og/_/ss/k=og.qtm.14WmFzvDkUg.L.W.O/m=qcwid/excm=qaaw,qadd,qaid,qein,qhaw,qhbr,qhch,qhga,qhid,qhin,qhpr/d=1/ed=1/ct=zgms/rs=AA2YrTsUdR6phhwi9aJhFbis7FI6IAjmMg
INFO:seleniumwire.handler:Capturing request: https://www.gstatic.com/og/_/js/k=og.qtm.en_US.Jn6hD4pATtI.O/rt=j/m=qabr,q_dnp,qcwid,qapid,qald/exm=qaaw,qadd,qaid,qein,qhaw,qhbr,qhch,qhga,qhid,qhin,qhpr/d=1/ed=1/rs=AA2YrTsYklP8lcczE-ijd6RDYU_tD3G0Ag
INFO:seleniumwire.handler:Capturing response: https://www.gstatic.com/og/_/ss/k=og.qtm.14WmFzvDkUg.L.W.O/m=qcwid/excm=qaaw,qadd,qaid,qein,qhaw,qhbr,qhch,qhga,qhid,qhin,qhpr/d=1/ed=1/ct=zgms/rs=AA2YrTsUdR6phhwi9aJhFbis7FI6IAjmMg 200 
INFO:seleniumwire.handler:Capturing response: https://www.gstatic.com/og/_/js/k=og.qtm.en_US.Jn6hD4pATtI.O/rt=j/m=qabr,q_dnp,qcwid,qapid,qald/exm=qaaw,qadd,qaid,qein,qhaw,qhbr,qhch,qhga,qhid,qhin,qhpr/d=1/ed=1/rs=AA2YrTsYklP8lcczE-ijd6RDYU_tD3G0Ag 200 
INFO:seleniumwire.handler:Capturing response: https://www.google.com/gen_204?ei=xtjOYZuOLfW78gLT6ZPYCg&vet=10ahUKEwibifrZ5431AhX1nVwKHdP0BKsQhJAHCBY..s&gl=GB&pc=SEARCH_HOMEPAGE&isMobile=false 204 
INFO:seleniumwire.handler:Capturing request: https://www.google.com/gen_204?s=webhp&t=aft&atyp=csi&ei=xtjOYZuOLfW78gLT6ZPYCg&rt=wsrt.417,aft.222,afti.222,prt.44&imn=5&ima=4&imad=0&aftp=600&bl=4JUY
INFO:seleniumwire.handler:Capturing response: https://www.google.com/gen_204?s=webhp&t=aft&atyp=csi&ei=xtjOYZuOLfW78gLT6ZPYCg&rt=wsrt.417,aft.222,afti.222,prt.44&imn=5&ima=4&imad=0&aftp=600&bl=4JUY 204 
INFO:seleniumwire.handler:Capturing request: https://apis.google.com/_/scs/abc-static/_/js/k=gapi.gapi.en.h3Hb0D_ghuM.O/m=gapi_iframes,googleapis_client/rt=j/sv=1/d=1/ed=1/rs=AHpOoo8HKYs3uYwO3D8vrT9sPLRNofSg0A/cb=gapi.loaded_0
INFO:seleniumwire.handler:Capturing response: https://apis.google.com/_/scs/abc-static/_/js/k=gapi.gapi.en.h3Hb0D_ghuM.O/m=gapi_iframes,googleapis_client/rt=j/sv=1/d=1/ed=1/rs=AHpOoo8HKYs3uYwO3D8vrT9sPLRNofSg0A/cb=gapi.loaded_0 200 
Sucess!
```
