### ISSUE TITLE
undetected_chromedriver not found.

### ISSUE THREAD

**Issue by ndbiaw** [wkeeling/selenium-wire#490]
even though I have installed undetected_chromedriver but I can't import it

from seleniumwire.undetected_chromedriver import Chrome, ChromeOptions
```
python main.py
Traceback (most recent call last):
  File "C:\Users\[REDACTED]\AppData\Local\Programs\Python\Python310\lib\site-packages\seleniumwire\undetected_chromedriver\__init__.py", line 2, in <module>
    import undetected_chromedriver as uc
  File "C:\Users\[REDACTED]\AppData\Local\Programs\Python\Python310\lib\site-packages\undetected_chromedriver\__init__.py", line 31, in <module>
    from . import v2
  File "C:\Users\[REDACTED]\AppData\Local\Programs\Python\Python310\lib\site-packages\undetected_chromedriver\v2.py", line 25, in <module>
    from .cdp import CDP
  File "C:\Users\[REDACTED]\AppData\Local\Programs\Python\Python310\lib\site-packages\undetected_chromedriver\cdp.py", line 6, in <module>
    from collections import Mapping, Sequence
ImportError: cannot import name 'Mapping' from 'collections' (C:\Users\[REDACTED]\AppData\Local\Programs\Python\Python310\lib\collections\__init__.py)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "[REDACTED]:\[REDACTED]\main.py", line 6, in <module>
    from [REDACTED] import (
  File "[REDACTED]:\[REDACTED]\[REDACTED].py", line 24, in <module>
    from seleniumwire.undetected_chromedriver import Chrome, ChromeOptions
  File "C:\Users\[REDACTED]\AppData\Local\Programs\Python\Python310\lib\site-packages\seleniumwire\undetected_chromedriver\__init__.py", line 4, in <module>
    raise ImportError(
ImportError: undetected_chromedriver not found. Install it with `pip install undetected_chromedriver`.

**Comment by wkeeling** [comment]
It could be because the version of pip you have used doesn’t align with the install of python you’re using. Try:

```
python -m pip install undetected_chromedriver
```

**Comment by ndbiaw** [comment]
> It could be because the version of pip you have used doesn’t align with the install of python you’re using. Try:
> 
> ```
> python -m pip install undetected_chromedriver
> ```


This error occurs on python 3.10 windows.

Downgrading to Python to 3.7 solves it.
