### ISSUE TITLE
Can't compile my code that uses seleniumwire

### ISSUE THREAD

**Issue by Avnsx** [wkeeling/selenium-wire#494]
Hey, I've recently written a code that uses seleniumwire and would like to compile it to an .exe using pyinstaller. Unfortunately it doesn't work as expected because I keep running into this error, but only with the compiled to a executable version of the code. Here's the Traceback:
```python
Traceback (most recent call last):
  File "automatic_configurator.py", line 295, in <module>
  File "undetected_chromedriver\__init__.py", line 57, in __new__
  File "seleniumwire\webdriver.py", line 200, in __init__
  File "seleniumwire\webdriver.py", line 35, in _setup_backend
  File "seleniumwire\backend.py", line 24, in create
  File "seleniumwire\server.py", line 28, in __init__
  File "seleniumwire\utils.py", line 159, in extract_cert_and_key
  File "pkgutil.py", line 637, in get_data
  File "PyInstaller\loader\pyimod03_importers.py", line 325, in get_data
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\pisto\\AppData\\Local\\Temp\\_MEI15522\\seleniumwire\\ca.crt'
```

Here's my source code before being compiled that does not cause the error: https://github.com/Avnsx/fansly/blob/main/automatic_configurator.py

Is there anything I could do to avoid this error from happening, in the compiled version?

Python 3.8.10 for Windows 10, Pyinstaller 4.8

Edit:
Uhh, I guess some people already have pointed this out multiple times. Have you been able to fix this properly yet?
Else I would be forced to use https://github.com/wkeeling/selenium-wire/issues/402#issuecomment-997417481 which is very hacky to do

**Comment by wkeeling** [comment]
So this is an issue with how pyinstaller handles the data files `ca.key` and `ca.crt` which are loaded by Selenium Wire at runtime through the standard library call `pkgutil.get_data()`.

I was able to reproduce the issue by creating a simple test script `test.py` which I compiled with the following command:

```bash
pyinstaller --onefile test.py
```

Running the binary created from that command gave me the same exception you're seeing:

```python
Traceback (most recent call last):                                                                                                                                                                                                            
  File "test.py", line 4, in <module>                                                                                                                                                                                                         
    driver = webdriver.Firefox()                                                                                       
  File "seleniumwire/webdriver.py", line 151, in __init__                                                                                                                                                                                     
  File "seleniumwire/webdriver.py", line 40, in _setup_backend                                                                                                                                                                                
  File "seleniumwire/backend.py", line 24, in create                                                                                                                                                                                          
  File "seleniumwire/server.py", line 28, in __init__                                                                                                                                                                                         
  File "seleniumwire/utils.py", line 159, in extract_cert_and_key                                                                                                                                                                             
  File "pkgutil.py", line 637, in get_data                                                                                                                                                                                                    
  File "PyInstaller/loader/pyimod03_importers.py", line 344, in get_data                                            
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/_MEIkX7dJi/seleniumwire/ca.crt' 
```

To resolve that I had to explicitly tell pyinstaller about the two data files and where they should live, by using the `--add-data` option:

```bash
pyinstaller --add-data 'ca.crt:seleniumwire' --add-data 'ca.key:seleniumwire' --onefile test.py
```

Note that you'll need to create the files [`ca.crt`](https://raw.githubusercontent.com/wkeeling/selenium-wire/master/seleniumwire/ca.crt) and [`ca.key`](https://raw.githubusercontent.com/wkeeling/selenium-wire/master/seleniumwire/ca.key) in your current working directory before you run the above command.

Once I'd done that I was able to run the binary without any issue.

**Comment by Avnsx** [comment]
> So this is an issue with how pyinstaller handles the data files `ca.key` and `ca.crt` which are loaded by Selenium Wire at runtime through the standard library call `pkgutil.get_data()`.
> 
> I was able to reproduce the issue by creating a simple test script `test.py` which I compiled with the following command:
> 
> ```shell
> pyinstaller --onefile test.py
> ```
> 
> Running the binary created from that command gave me the same exception you're seeing:
> 
> ```python
> Traceback (most recent call last):                                                                                                                                                                                                            
>   File "test.py", line 4, in <module>                                                                                                                                                                                                         
>     driver = webdriver.Firefox()                                                                                       
>   File "seleniumwire/webdriver.py", line 151, in __init__                                                                                                                                                                                     
>   File "seleniumwire/webdriver.py", line 40, in _setup_backend                                                                                                                                                                                
>   File "seleniumwire/backend.py", line 24, in create                                                                                                                                                                                          
>   File "seleniumwire/server.py", line 28, in __init__                                                                                                                                                                                         
>   File "seleniumwire/utils.py", line 159, in extract_cert_and_key                                                                                                                                                                             
>   File "pkgutil.py", line 637, in get_data                                                                                                                                                                                                    
>   File "PyInstaller/loader/pyimod03_importers.py", line 344, in get_data                                            
> FileNotFoundError: [Errno 2] No such file or directory: '/tmp/_MEIkX7dJi/seleniumwire/ca.crt' 
> ```
> 
> To resolve that I had to explicitly tell pyinstaller about the two data files and where they should live, by using the [`--add-data`](https://pyinstaller.readthedocs.io/en/stable/usage.html#cmdoption-add-data) option:
> 
> ```shell
> pyinstaller --add-data 'ca.crt:seleniumwire' --add-data 'ca.key:seleniumwire' --onefile test.py
> ```
> 
> Note that you'll need to create the files [`ca.crt`](https://raw.githubusercontent.com/wkeeling/selenium-wire/master/seleniumwire/ca.crt) and [`ca.key`](https://raw.githubusercontent.com/wkeeling/selenium-wire/master/seleniumwire/ca.key) in your current working directory before you run the above command.
> 
> Once I'd done that I was able to run the binary without any issue.
> 
> Note that Windows uses `;` as a path separator - so if on Windows the options would be `--add-data 'ca.key;seleniumwire'` and `--add-data 'ca.key;seleniumwire'`

I mean the way I fixed the issue equally good https://github.com/Avnsx/fansly/blob/e49a3efc3cb2d7d7df6547a487fb8dbf3dad22ee/automatic_configurator.py#L325

I was looking for a effective bug fix, by patching seleniumwire source so that this bug does not happen anymore in first place instead of trying to "band aids" around it
