### ISSUE TITLE
Broken Pipe Errors Popup every now and then

### ISSUE THREAD

**Issue by appunni-dishq** [wkeeling/selenium-wire#5]
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 53178)
Traceback (most recent call last):
  File "/usr/lib/python3.5/socketserver.py", line 625, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.5/socketserver.py", line 354, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/home/user/.virtualenvs/project/lib/python3.5/site-packages/seleniumwire/proxy/proxy2.py", line 65, in __init__
    super().__init__(*args, **kwargs)
  File "/usr/lib/python3.5/socketserver.py", line 681, in __init__
    self.handle()
  File "/usr/lib/python3.5/http/server.py", line 424, in handle
    self.handle_one_request()
  File "/usr/lib/python3.5/http/server.py", line 410, in handle_one_request
    method()
  File "/home/user/.virtualenvs/project/lib/python3.5/site-packages/seleniumwire/proxy/proxy2.py", line 224, in do_GET
    self.wfile.write(res_body)
  File "/usr/lib/python3.5/socket.py", line 593, in write
    return self._sock.send(b)
  File "/usr/lib/python3.5/ssl.py", line 861, in send
    return self._sslobj.write(data)
  File "/usr/lib/python3.5/ssl.py", line 586, in write
    return self._sslobj.write(data)
BrokenPipeError: [Errno 32] Broken pipe
Successfully started content_tester for url
Fatal Python error: could not acquire lock for <_io.BufferedWriter name='<stdout>'> at interpreter shutdown, possibly due to daemon threads

Thread 0x00007fa214bc8700 (most recent call first):
  File "/usr/lib/python3.5/ssl.py", line 575 in read
  File "/usr/lib/python3.5/ssl.py", line 791 in read
  File "/usr/lib/python3.5/ssl.py", line 929 in recv_into
  File "/usr/lib/python3.5/socket.py", line 575 in readinto
  File "/usr/lib/python3.5/http/client.py", line 258 in _read_status
  File "/usr/lib/python3.5/http/client.py", line 297 in begin
  File "/usr/lib/python3.5/http/client.py", line 1197 in getresponse
  File "/home/user/.virtualenvs/project/lib/python3.5/site-packages/seleniumwire/proxy/proxy2.py", line 179 in do_GET
  File "/usr/lib/python3.5/http/server.py", line 410 in handle_one_request
  File "/usr/lib/python3.5/http/server.py", line 424 in handle
  File "/usr/lib/python3.5/socketserver.py", line 681 in __init__
  File "/home/user/.virtualenvs/project/lib/python3.5/site-packages/seleniumwire/proxy/proxy2.py", line 65 in __init__
  File "/usr/lib/python3.5/socketserver.py", line 354 in finish_request
  File "/usr/lib/python3.5/socketserver.py", line 625 in process_request_thread
  File "/usr/lib/python3.5/threading.py", line 862 in run
  File "/usr/lib/python3.5/threading.py", line 914 in _bootstrap_inner
  File "/usr/lib/python3.5/threading.py", line 882 in _bootstrap

Thread 0x00007fa216bcc700 (most recent call first):
  File "/usr/lib/python3.5/socketserver.py", line 375 in handle_error
  File "/home/user/.virtualenvs/project/lib/python3.5/site-packages/seleniumwire/proxy/proxy2.py", line 49 in handle_error
  File "/usr/lib/python3.5/socketserver.py", line 628 in process_request_thread
  File "/usr/lib/python3.5/threading.py", line 862 in run
  File "/usr/lib/python3.5/threading.py", line 914 in _bootstrap_inner
  File "/usr/lib/python3.5/threading.py", line 882 in _bootstrap

Current thread 0x00007fa22b150700 (most recent call first):
Aborted (core dumped)

**Comment by wkeeling** [comment]
Many thanks for raising this. `BrokenPipeError`s can happen when the test ends (and interpreter process ends) whilst the underlying proxy is still handling a previous request. This is normally harmless and I suppressed `BrokenPipeError`s by logging them at debug level. However, in your case it seems that the error may have crashed the interpreter process - judging by the "core dumped" - which may explain why you're seeing it.

I'll do some digging and see if there's a better way of handling the situation.

**Comment by appunni-dishq** [comment]
It seems like it was happening more often when I was using driver.close(), I shifter to driver.quit() and things are looking better now
