### ISSUE TITLE
ERROR WITH NEW ENVIRONMENT

### ISSUE THREAD

**Issue by FranciscoPalomares** [wkeeling/selenium-wire#551]
Message: Service /Users/pacopalomares/.wdm/drivers/chromedriver/mac64_m1/101.0.4951.41/chromedriver unexpectedly exited. Status code was: -9

options_chrome = webdriver.ChromeOptions()
options = {'disable_encoding': True}
driver = webdriver.Chrome(ChromeDriverManager().install(), seleniumwire_options=options,
                              chrome_options=options_chrome)

**Comment by wkeeling** [comment]
Do you have the full traceback you can share?

**Comment by always-beta** [comment]
I have the same issue on a Macbook M1 chip.

```
[06-27 13:14:48 seleniumwire.storage]: Using default request storage
[06-27 13:14:48 seleniumwire.backend]: Created proxy listening on ::ffff:127.0.0.1:64442
[06-27 13:14:48 seleniumwire.undetected_chromedriver.webdriver]: Using undetected_chromedriver
Traceback (most recent call last):
  File "tcpjw.py", line 152, in <module>
  File "runner.py", line 25, in __init__
  File "seleniumwire/undetected_chromedriver/webdriver.py", line 61, in __init__
  File "undetected_chromedriver/__init__.py", line 401, in __init__
  File "selenium/webdriver/chrome/webdriver.py", line 70, in __init__
  File "selenium/webdriver/chromium/webdriver.py", line 89, in __init__
  File "selenium/webdriver/common/service.py", line 98, in start
  File "selenium/webdriver/common/service.py", line 110, in assert_process_still_running
selenium.common.exceptions.WebDriverException: Message: Service /Users/xxx/Desktop/project/tcpjw/chromedriver unexpectedly exited. Status code was: -9

```

The chromedriver itself works fine.
And the issue seems started after chrome auto upgraded from 101 to 103, but downgraded to 101 doesn't solve the issue.
