### ISSUE TITLE
Socket of selenium-wire or proxy2 instance can't be killed

### ISSUE THREAD

**Issue by Nicolas-Brossard** [wkeeling/selenium-wire#57]
Hi,

I'm testing selenium-wire and it seems on OSX the websocket / proxy instance can't be killed when the webdriver is closing.
Seleniumwire_options works fine when it's the first instance, after the Seleniumwire_options configuration is destroy or override by something.
The result is the proxy configuration work only one time.

configuration : 

OSX 10.14.5 
Python 3.7

Thanks a lot

**Comment by Nicolas-Brossard** [comment]
When i add :

    'suppress_connection_errors': False  # Show full tracebacks for any connection errors

I have more informations.

`Exception happened during processing of request from ('127.0.0.1', 51365)
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/socketserver.py", line 650, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python3.7/site-packages/seleniumwire/proxy/handler.py", line 135, in __init__
    raise e
  File "/usr/local/lib/python3.7/site-packages/seleniumwire/proxy/handler.py", line 127, in __init__
    super().__init__(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/seleniumwire/proxy/proxy2.py", line 65, in __init__
    super().__init__(*args, **kwargs)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/socketserver.py", line 720, in __init__
    self.handle()
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/server.py", line 428, in handle
    self.handle_one_request()
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/server.py", line 414, in handle_one_request
    method()
  File "/usr/local/lib/python3.7/site-packages/seleniumwire/proxy/proxy2.py", line 215, in do_GET
    self.wfile.write(res_body)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/socket.py", line 607, in write
    return self._sock.send(b)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 984, in send
    return self._sslobj.write(data)
BrokenPipeError: [Errno 32] Broken pipe`
