### ISSUE TITLE
error at " pip install selenium-wire"

### ISSUE THREAD

**Issue by GildedHonour** [wkeeling/selenium-wire#573]
Python 3.10.5
pip 21.0

```
 pip install selenium-wire
Traceback (most recent call last):
  File "/usr/bin/pip", line 33, in <module>
    sys.exit(load_entry_point('pip==21.0', 'console_scripts', 'pip')())
  File "/usr/lib/python3.10/site-packages/pip/_internal/cli/main.py", line 71, in main
    command = create_command(cmd_name, isolated=("--isolated" in cmd_args))
  File "/usr/lib/python3.10/site-packages/pip/_internal/commands/__init__.py", line 96, in create_command
    module = importlib.import_module(module_path)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/lib/python3.10/site-packages/pip/_internal/commands/install.py", line 12, in <module>
    from pip._internal.cache import WheelCache
  File "/usr/lib/python3.10/site-packages/pip/_internal/cache.py", line 15, in <module>
    from pip._internal.utils.temp_dir import TempDirectory, tempdir_kinds
  File "/usr/lib/python3.10/site-packages/pip/_internal/utils/temp_dir.py", line 9, in <module>
    from pip._vendor.six import ensure_text
ImportError: cannot import name 'ensure_text' from 'six' (/home/alex/.local/lib/python3.10/site-packages/six.py)
```

**Comment by wkeeling** [comment]
Did you manage to solve this? I haven't been able to reproduce with Python 3.10, but looking online it seems as though the issue is caused if an old version of six is installed in your environment. If you're still having a problem you could try upgrading `six` in with:

```shell
pip install --upgrade six
```
