### ISSUE TITLE
Having "Timed out receiving message from renderer" after updating my system

### ISSUE THREAD

**Issue by carlosagh96** [wkeeling/selenium-wire#579]
This is (sort of) the code i'm running:
```
import time
import sys

from seleniumwire import webdriver
from seleniumwire.webdriver import ChromeOptions

try:
	url_target=sys.argv[1]
except:
	exit()

_cd_opts=ChromeOptions()
_cd_opts.add_argument("--ignore-certificate-errors")
_cd_opts.add_argument("--headless")
_cd_opts.add_argument("--disable-gpu")
_cd_opts.add_argument("--disable-extensions")
_cd_opts.add_argument("--no-sandbox")

driver=webdriver.Chrome(options=_cd_opts)

print("GET",url_target)
driver.get(url_target)
print("waiting 1 sec...")
time.sleep(1)

scans=30
while scans>0:
	for request in driver.requests:
		if request.response:
			if "something_i_need" in request.url:
				print("Found it!",request.url)
				scans=0

		if scans==0:
			break

	if scans==0:
		break

	scans=scans-1
	time.sleep(1)

driver.quit()
```
The code gets stuck at the driver.get(), and then fails because of Timeout, it never reaches the rest of the code
```
Traceback (most recent call last):
  File "/bot/./1449424315/chillx.py", line 19, in 
    driver.get(url_target)
  File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 447, in get
    self.execute(Command.GET, {'url': url})
  File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 435, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 299.012
  (Session info: headless chrome=103.0.5060.134)
Stacktrace:
#0 0x558f80332a33 
#1 0x558f80128206 
#2 0x558f80112e75 
#3 0x558f80111c62 
#4 0x558f80112289 
#5 0x558f80125008 
#6 0x558f801258a2 
#7 0x558f8013042f 
#8 0x558f8013478a 
#9 0x558f801125e6 
#10 0x558f80130277 
#11 0x558f80198285 
#12 0x558f80185683 
#13 0x558f801552ab 
#14 0x558f80156ade 
#15 0x558f8036fafd 
#16 0x558f80372333 
#17 0x558f80372029 
#18 0x558f80372942 
#19 0x558f8035fe7b 
#20 0x558f80372bc1 
#21 0x558f80354c37 
#22 0x558f803899c5 
#23 0x558f80389b63 
#24 0x558f803a4121 
#25 0x7f585821cea7
```

Before I had this problem, I was using Debian 10 with it's corresponding version of cromium + chrome-driver, with the same options

This is what I have now:
I'm using python 3.9.6 at Debian 11
selenium 4.3.0
selenium-wire 4.6.5
chromium 103.0.5060.134-1~deb11u1
chrome-driver 103.0.5060.134-1~deb11u1
OpenSSL 1.1.1n  15 Mar 2022 (Library: OpenSSL 1.1.1k  25 Mar 2021)

**Comment by carlosagh96** [comment]
Fixed it
added this right after making teh driver, and try:except: block to the driver.get()
```
driver.set_page_load_timeout(5)
```
It was a site specific thing in the end
