### ISSUE TITLE
H11 Headers error?

### ISSUE THREAD

**Issue by Rapid1898-code** [wkeeling/selenium-wire#594]
Hello - i try to run the module using the following code:

```
from seleniumwire import webdriver  # Import from seleniumwire
driver = webdriver.Chrome()
driver.get('https://www.google.com')
```

But i get this error:

```
$ python test1.py
Traceback (most recent call last):
  File "C:\DEV\Fiverr\TRY\abadvany\test1.py", line 1, in <module>
    from seleniumwire import webdriver  # Import from seleniumwire
  File "C:\DEV\.venv\test\lib\site-packages\seleniumwire\webdriver.py", line 27, in <module>
    from seleniumwire import backend, utils
  File "C:\DEV\.venv\test\lib\site-packages\seleniumwire\backend.py", line 4, in <module>
    from seleniumwire.server import MitmProxy
  File "C:\DEV\.venv\test\lib\site-packages\seleniumwire\server.py", line 7, in <module>
    from seleniumwire.thirdparty.mitmproxy import addons
  File "C:\DEV\.venv\test\lib\site-packages\seleniumwire\thirdparty\mitmproxy\addons\__init__.py", line 1, in <module>
    from seleniumwire.thirdparty.mitmproxy.addons import core
  File "C:\DEV\.venv\test\lib\site-packages\seleniumwire\thirdparty\mitmproxy\addons\core.py", line 5, in <module>
    from seleniumwire.thirdparty.mitmproxy import command, ctx, exceptions, optmanager, platform
  File "C:\DEV\.venv\test\lib\site-packages\seleniumwire\thirdparty\mitmproxy\ctx.py", line 2, in <module>       
    import seleniumwire.thirdparty.mitmproxy.master
  File "C:\DEV\.venv\test\lib\site-packages\seleniumwire\thirdparty\mitmproxy\master.py", line 7, in <module>    
    from seleniumwire.thirdparty.mitmproxy import (
  File "C:\DEV\.venv\test\lib\site-packages\seleniumwire\thirdparty\mitmproxy\addonmanager.py", line 8, in <module>
    from seleniumwire.thirdparty.mitmproxy import controller, eventsequence, exceptions
  File "C:\DEV\.venv\test\lib\site-packages\seleniumwire\thirdparty\mitmproxy\eventsequence.py", line 3, in <module>
    from seleniumwire.thirdparty.mitmproxy import controller, http, tcp, websocket
  File "C:\DEV\.venv\test\lib\site-packages\seleniumwire\thirdparty\mitmproxy\websocket.py", line 5, in <module> 
    from wsproto.frame_protocol import CloseReason, Opcode
  File "C:\DEV\.venv\test\lib\site-packages\wsproto\__init__.py", line 9, in <module>
    from .connection import Connection, ConnectionState, ConnectionType
  File "C:\DEV\.venv\test\lib\site-packages\wsproto\connection.py", line 23, in <module>
    from .utilities import LocalProtocolError
  File "C:\DEV\.venv\test\lib\site-packages\wsproto\utilities.py", line 12, in <module>
    from h11._headers import Headers as H11Headers
ImportError: cannot import name 'Headers' from 'h11._headers' (C:\DEV\.venv\test\lib\site-packages\h11\_headers.py)
```

I am trying this with
```
Python 3.9.7
selenium-wire             4.6.5
h11                       0.9.0
```

Any suggestions why this is happening?

**Comment by nrllh** [comment]
I think it's not a `selenium-wire` related issue. Try to reinstall [h11 ](https://pypi.org/project/h11/) package, it may help you.

**Comment by Rapid1898-code** [comment]
Yes you are right - i made a new venv and not it works without errors.
Thanks for your reply.
