### ISSUE TITLE
Error when using Python 3.10

### ISSUE THREAD

**Issue by Bool13** [wkeeling/selenium-wire#598]
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 1078, in _handle_fromlist
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Program Files\Python310\lib\site-packages\seleniumwire\webdriver.py", line 28, in <module>
    from seleniumwire import backend, utils
  File "C:\Program Files\Python310\lib\site-packages\seleniumwire\backend.py", line 4, in <module>
    from seleniumwire.server import MitmProxy
  File "C:\Program Files\Python310\lib\site-packages\seleniumwire\server.py", line 5, in <module>
    from seleniumwire.handler import InterceptRequestHandler
  File "C:\Program Files\Python310\lib\site-packages\seleniumwire\handler.py", line 5, in <module>
    from seleniumwire import har
  File "C:\Program Files\Python310\lib\site-packages\seleniumwire\har.py", line 11, in <module>
    from seleniumwire.thirdparty.mitmproxy import connections
  File "C:\Program Files\Python310\lib\site-packages\seleniumwire\thirdparty\mitmproxy\connections.py", line 7, in <module>
    import socks
  File "C:\Program Files\Python310\lib\site-packages\socks.py", line 58, in <module>
    from collections import Callable
ImportError: cannot import name 'Callable' from 'collections' (C:\Program Files\Python310\lib\collections\__init__.py)

**Comment by wkeeling** [comment]
Looks like you're running an old version of PySocks. Selenium Wire mandates at least version `1.7.1` (your version looks like it's `1.6.8` or earlier). 

You can upgrade with:
```
pip install pysocks==1.7.1
```
