### ISSUE TITLE
driver.quit() raises connection exceptions.

### ISSUE THREAD

**Issue by ifeelagood** [wkeeling/selenium-wire#621]
Hi. This error only occurs when using selenium-wire, with seleniumwire.webdriver.Firefox and seleniumwire.webdriver.undetected_chromedriver. Not sure about regular chromedriver. When calling `driver.quit()`, exceptions are raised from `urllib3.connectionpool`, which eventually ends excecution with  `OSError: [WinError 6] The handle is invalid`

Python version: 3.11.0
selenium-wire version: 5.1.0
webdriver: seleniumwire.webdriver.Firefox, seleniumwire.undetected_chromedriver

```
while not has_code:
    for request in driver.requests:
        if request.response:
            if request.url.startswith(REDIRECT_URI):
                has_code = True
                self.logger.debug("Found redirect url: {}".format(request.url))
                callback_url = request.url
                break

# wait for requests to finish, then close driver
self.logger.debug("Closing webdriver")
driver.quit()
```

Error Traceback:

```
__main__: [DEBUG] Found redirect url: REDACTED
__main__: [DEBUG] Closing webdriver
urllib3.connectionpool: [WARNING] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001824FFACE50>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/14ccf2be0c3572c6be1a555b14727b88/window
urllib3.connectionpool: [WARNING] Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001824FFA5290>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/14ccf2be0c3572c6be1a555b14727b88/window
urllib3.connectionpool: [WARNING] Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000182502B8390>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/14ccf2be0c3572c6be1a555b14727b88/window
Traceback (most recent call last):
  File "C:\Users\{REDACTED}\scoop\apps\python\current\Lib\site-packages\urllib3\connection.py", line 174, in _new_conn
    conn = connection.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\{REDACTED}\scoop\apps\python\current\Lib\site-packages\urllib3\util\connection.py", line 95, in create_connection
    raise err
  File "C:\Users\{REDACTED}\scoop\apps\python\current\Lib\site-packages\urllib3\util\connection.py", line 85, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\{REDACTED}\scoop\apps\python\current\Lib\site-packages\urllib3\connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
                       ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\{REDACTED}\scoop\apps\python\current\Lib\site-packages\urllib3\connectionpool.py", line 398, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "C:\Users\{REDACTED}\scoop\apps\python\current\Lib\site-packages\urllib3\connection.py", line 239, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "C:\Users\{REDACTED}\scoop\apps\python\current\Lib\http\client.py", line 1282, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Users\{REDACTED}\scoop\apps\python\current\Lib\http\client.py", line 1328, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Users\{REDACTED}\scoop\apps\python\current\Lib\http\client.py", line 1277, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Users\{REDACTED}\scoop\apps\python\current\Lib\http\client.py", line 1037, in _send_output
    self.send(msg)
  File "C:\Users\{REDACTED}\scoop\apps\python\current\Lib\http\client.py", line 975, in send
    self.connect()
  File "C:\Users\{REDACTED}\scoop\apps\python\current\Lib\site-packages\urllib3\connection.py", line 205, in connect
    conn = self._new_conn()
           ^^^^^^^^^^^^^^^^
  File "C:\Users\{REDACTED}\scoop\apps\python\current\Lib\site-packages\urllib3\connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x00000182506C1BD0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\pixiv_scraper\PixivOAuth.py", line 128, in <module>
    resp = auth.login("{REDACTED}", "{REDACTED}")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\pixiv_scraper\PixivOAuth.py", line 95, in login
    driver.close()
  File "C:\Users\{REDACTED}\scoop\apps\python\current\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 551, in close
    self.execute(Command.CLOSE)
  File "C:\Users\{REDACTED}\scoop\apps\python\current\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 427, in execute
    response = self.command_executor.execute(driver_command, params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\{REDACTED}\scoop\apps\python\current\Lib\site-packages\selenium\webdriver\remote\remote_connection.py", line 344, in execute
    return self._request(command_info[0], url, body=data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\{REDACTED}\scoop\apps\python\current\Lib\site-packages\selenium\webdriver\remote\remote_connection.py", line 366, in _request
    response = self._conn.request(method, url, body=body, headers=headers)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\{REDACTED}\scoop\apps\python\current\Lib\site-packages\urllib3\request.py", line 74, in request
    return self.request_encode_url(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\{REDACTED}\scoop\apps\python\current\Lib\site-packages\urllib3\request.py", line 96, in request_encode_url
    return self.urlopen(method, url, **extra_kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\{REDACTED}\scoop\apps\python\current\Lib\site-packages\urllib3\poolmanager.py", line 376, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\{REDACTED}\scoop\apps\python\current\Lib\site-packages\urllib3\connectionpool.py", line 815, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "C:\Users\{REDACTED}\scoop\apps\python\current\Lib\site-packages\urllib3\connectionpool.py", line 815, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "C:\Users\{REDACTED}\scoop\apps\python\current\Lib\site-packages\urllib3\connectionpool.py", line 815, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "C:\Users\{REDACTED}\scoop\apps\python\current\Lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
o connection could be made because the target machine actively refused it'))
urllib3.connectionpool: [WARNING] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000182506C2710>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/14ccf2be0c3572c6be1a555b14727b88
urllib3.connectionpool: [WARNING] Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000182506C16D0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/14ccf2be0c3572c6be1a555b14727b88
urllib3.connectionpool: [WARNING] Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000182506C0E90>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/14ccf2be0c3572c6be1a555b14727b88
Exception ignored in: <function Chrome.__del__ at 0x000001824E9FCA40>
Traceback (most recent call last):
  File "C:\Users\{REDACTED}\scoop\apps\python\current\Lib\site-packages\undetected_chromedriver\__init__.py", line 657, in __del__
  File "C:\Users\{REDACTED}\scoop\apps\python\current\Lib\site-packages\seleniumwire\webdriver.py", line 68, in quit
  File "C:\Users\{REDACTED}\scoop\apps\python\current\Lib\site-packages\undetected_chromedriver\__init__.py", line 645, in quit
OSError: [WinError 6] The handle is invalid
```

Any help would be appreciated, thanks!

**Comment by DUB1401** [comment]
I also have this problem.

### System
_Python 3.11.4_
_Windows 11 23H2_

### Packages
_Selenium 4.11.2_
_selenium-wire 5.1.0_
_undetected-chromedriver 3.5.2_

### Traceback
```
Traceback (most recent call last):
  File "C:\Program Files\Python311\Lib\site-packages\undetected_chromedriver\__init__.py", line 843, in __del__
  File "C:\Program Files\Python311\Lib\site-packages\seleniumwire\webdriver.py", line 68, in quit
  File "C:\Program Files\Python311\Lib\site-packages\undetected_chromedriver\__init__.py", line 798, in quit
OSError: [WinError 6] The handle is invalid
```
