### ISSUE TITLE
about connect proxy with authentication user name & password urgently

### ISSUE THREAD

**Issue by ahmedabdelhamedz** [wkeeling/selenium-wire#622]
`import time
import seleniumwire.undetected_chromedriver as uc

if __name__ == "__main__":
    chrome_options = uc.ChromeOptions()
    # here your chrome options

    seleniumwire_options = {
        "proxy": {
            "https": "https://user:pass@ip:port"
        }
    }

    driver = uc.Chrome(
        options=chrome_options, seleniumwire_options=seleniumwire_options
    )
    driver.get("https://api.myip.com/")
    time.sleep(10)`

i found this error code 

C:\Users\pcpc\PycharmProjects\untitled\venv\Scripts\python.exe C:/Users/pcpc/PycharmProjects/untitled/script.py
Traceback (most recent call last):
  File "C:\Users\pcpc\PycharmProjects\untitled\script.py", line 8, in <module>
    from seleniumwire import webdriver
  File "C:\Users\pcpc\PycharmProjects\untitled\venv\lib\site-packages\seleniumwire\webdriver.py", line 28, in <module>
    from seleniumwire import backend, utils
  File "C:\Users\pcpc\PycharmProjects\untitled\venv\lib\site-packages\seleniumwire\backend.py", line 4, in <module>
    from seleniumwire.server import MitmProxy
  File "C:\Users\pcpc\PycharmProjects\untitled\venv\lib\site-packages\seleniumwire\server.py", line 5, in <module>
    from seleniumwire.handler import InterceptRequestHandler
  File "C:\Users\pcpc\PycharmProjects\untitled\venv\lib\site-packages\seleniumwire\handler.py", line 5, in <module>
    from seleniumwire import har
  File "C:\Users\pcpc\PycharmProjects\untitled\venv\lib\site-packages\seleniumwire\har.py", line 12, in <module>
    from seleniumwire.thirdparty.mitmproxy.http import HTTPFlow
  File "C:\Users\pcpc\PycharmProjects\untitled\venv\lib\site-packages\seleniumwire\thirdparty\mitmproxy\http.py", line 7, in <module>
    from seleniumwire.thirdparty.mitmproxy.net import http
  File "C:\Users\pcpc\PycharmProjects\untitled\venv\lib\site-packages\seleniumwire\thirdparty\mitmproxy\net\http\__init__.py", line 1, in <module>
    from seleniumwire.thirdparty.mitmproxy.net.http import http1, http2, multipart, status_codes
  File "C:\Users\pcpc\PycharmProjects\untitled\venv\lib\site-packages\seleniumwire\thirdparty\mitmproxy\net\http\http1\__init__.py", line 2, in <module>
    from .read import (connection_close, expected_http_body_size, read_body, read_request, read_request_head,
  File "C:\Users\pcpc\PycharmProjects\untitled\venv\lib\site-packages\seleniumwire\thirdparty\mitmproxy\net\http\http1\read.py", line 7, in <module>
    from seleniumwire.thirdparty.mitmproxy.net.http import (headers, request,
  File "C:\Users\pcpc\PycharmProjects\untitled\venv\lib\site-packages\seleniumwire\thirdparty\mitmproxy\net\http\request.py", line 8, in <module>
    from seleniumwire.thirdparty.mitmproxy.net.http import cookies, message, multipart
  File "C:\Users\pcpc\PycharmProjects\untitled\venv\lib\site-packages\seleniumwire\thirdparty\mitmproxy\net\http\message.py", line 6, in <module>
    from seleniumwire.thirdparty.mitmproxy.net.http import encoding
  File "C:\Users\pcpc\PycharmProjects\untitled\venv\lib\site-packages\seleniumwire\thirdparty\mitmproxy\net\http\encoding.py", line 12, in <module>
    import brotli
  File "C:\Users\pcpc\PycharmProjects\untitled\venv\lib\site-packages\brotli.py", line 8, in <module>
    import _brotli
ImportError: DLL load failed while importing _brotli: The specified module could not be found.

Process finished with exit code 1

please can you explain to me how to fix this error ? @wkeeling @royopa @nck @joelluijmes @mynameisfiber

**Comment by ahmedabdelhamedz** [comment]
thanks i fix it by download microsoft c++ last version but ssl certificate is not secured how can i fix this problem

**Comment by wkeeling** [comment]
The certificate warning should disappear if you [install Selenium Wire's root certificate](https://github.com/wkeeling/selenium-wire#certificates).

**Comment by ahmedabdelhamedz** [comment]
> The certificate warning should disappear if you [install Selenium Wire's root certificate](https://github.com/wkeeling/selenium-wire#certificates).

how can i connect this certificate with undetected chrome driver ?
https://raw.githubusercontent.com/wkeeling/selenium-wire/master/seleniumwire/ca.crt
@wkeeling

**Comment by wkeeling** [comment]
You install the certificate into your browser's "trusted root certificates":
![image](https://user-images.githubusercontent.com/1295116/202152290-508f2e3b-544f-41f1-b647-bde7104a12ac.png)

**Comment by ahmedabdelhamedz** [comment]
> You install the certificate into your browser's "trusted root certificates":
> 
> ![image](https://user-images.githubusercontent.com/1295116/202152290-508f2e3b-544f-41f1-b647-bde7104a12ac.png)

Common Name (CN)	Selenium Wire CA
Organization (O)	<Not Part Of Certificate>
Organizational Unit (OU)	<Not Part Of Certificate>

please sir why it take certificate from selenium wire ca not from certificate of each website as a normal browser?

**Comment by wkeeling** [comment]
Because Selenium Wire has to decrypt the HTTPS request in order to capture it. To perform the decryption (and encryption for outbound traffic) Selenium Wire acts as a "man in the middle" and uses its own root certificate for encryption/decryption.

**Comment by ahmedabdelhamedz** [comment]
@wkeeling how can i make it get real certificate of website not seleniumwire ca certificate ? as a normal browser to not  be detected

**Comment by wkeeling** [comment]
That's not possible if you're using Selenium Wire - it will always have to use it's own CA certificate for the purposes of interception and capture.

**Comment by ahmedabdelhamedz** [comment]
> That's not possible if you're using Selenium Wire - it will always have to use it's own CA certificate for the purposes of interception and capture.

@wkeeling  please sir are there any other solution to connect proxy with authentication by undetected chrome driver without using seleniumwire or plugin ?
