### ISSUE TITLE
error on change ip of machine

### ISSUE THREAD

**Issue by ahmedabdelhamedz** [wkeeling/selenium-wire#625]
import time
import seleniumwire.undetected_chromedriver as uc

if __name__ == '__main__':
    opts = uc.ChromeOptions()
    # here your chrome options

    seleniumwire_options = {
        "proxy": {
            "https": "https://user:pass@ip:port"
        },

        'addr': '192.168.0.10'
    }

    driver = uc.Chrome(options=opts, seleniumwire_options=seleniumwire_options)

    driver.get("https://api.myip.com/")
    input()

error code :

C:\Users\pcpc\PycharmProjects\untitled\venv\Scripts\python.exe C:/Users/pcpc/PycharmProjects/untitled/script.py
Traceback (most recent call last):
  File "C:\Users\pcpc\PycharmProjects\untitled\script.py", line 16, in <module>
    driver = uc.Chrome(options=opts, seleniumwire_options=seleniumwire_options)
  File "C:\Users\pcpc\PycharmProjects\untitled\venv\lib\site-packages\seleniumwire\undetected_chromedriver\webdriver.py", line 32, in __init__
    config = self._setup_backend(seleniumwire_options)
  File "C:\Users\pcpc\PycharmProjects\untitled\venv\lib\site-packages\seleniumwire\webdriver.py", line 41, in _setup_backend
    self.backend = backend.create(
  File "C:\Users\pcpc\PycharmProjects\untitled\venv\lib\site-packages\seleniumwire\backend.py", line 24, in create
    backend = MitmProxy(addr, port, options)
  File "C:\Users\pcpc\PycharmProjects\untitled\venv\lib\site-packages\seleniumwire\server.py", line 49, in __init__
    mitmproxy_opts.update(
  File "C:\Users\pcpc\PycharmProjects\untitled\venv\lib\site-packages\seleniumwire\thirdparty\mitmproxy\optmanager.py", line 223, in update
    u = self.update_known(**kwargs)
  File "C:\Users\pcpc\PycharmProjects\untitled\venv\lib\site-packages\seleniumwire\thirdparty\mitmproxy\optmanager.py", line 214, in update_known
    self._options[k].set(v)
  File "C:\Users\pcpc\PycharmProjects\untitled\venv\lib\site-packages\seleniumwire\thirdparty\mitmproxy\optmanager.py", line 55, in set
    typecheck.check_option_type(self.name, value, self.typespec)
  File "C:\Users\pcpc\PycharmProjects\untitled\venv\lib\site-packages\seleniumwire\thirdparty\mitmproxy\utils\typecheck.py", line 76, in check_option_type
    raise e
TypeError: Expected <class 'str'> for listen_host, but got <class 'set'>.
Exception ignored in: <function Chrome.__del__ at 0x0000006BB478AEE0>
Traceback (most recent call last):
  File "C:\Users\pcpc\PycharmProjects\untitled\venv\lib\site-packages\undetected_chromedriver\__init__.py", line 657, in __del__
  File "C:\Users\pcpc\PycharmProjects\untitled\venv\lib\site-packages\seleniumwire\webdriver.py", line 67, in quit
  File "C:\Users\pcpc\PycharmProjects\untitled\venv\lib\site-packages\undetected_chromedriver\__init__.py", line 441, in __getattribute__
AttributeError: 'Chrome' object has no attribute 'backend'

Process finished with exit code 1

when i try to change ip of machine appear to me this error how can i fix this problem please?

**Comment by mynameisfiber** [comment]
@ahmedabdelhamedz could you please stop randomly @-spamming?

**Comment by ahmedabdelhamedz** [comment]
> @ahmedabdelhamedz could you please stop randomly @-spamming?

ok for sure i am sorry
