### ISSUE TITLE
ProxyRequestHandler appends an extra Content-Length tag when body has been modified

### ISSUE THREAD

**Issue by pr11t** [wkeeling/selenium-wire#79]
Hi!

I was trying to change a pages content using custom_response_handler, but Firefox kept giving me corruptedContentError: 
```2019-11-18 21:03:25,270 DEBUG https://www.zombo.com/ 200
2019-11-18 21:03:25,423 DEBUG http://127.0.0.1:39549 "POST /session/994ca285-44ee-4a20-bbcb-ab0087dd9798/url HTTP/1.1" 500 545
2019-11-18 21:03:25,423 DEBUG Finished Request
Traceback (most recent call last):
  File "proj/runner.py", line 29, in <module>
    r.main()
  File "proj/runner.py", line 21, in main
    method(**flowitem['args'])
  File "/home/priit/Repositories/proj/proj/actions.py", line 144, in driver_load_url
    self.browser.get(url)
  File "/home/priit/Repositories/proj/venv/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/priit/Repositories/proj/venv/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/priit/Repositories/proj/venv/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: Reached error page: about:neterror?e=corruptedContentErrorv2&u=https%3A//www.zombo.com/&c=UTF-8&f=regular&d=The%20site%20at%20https%3A//www.zombo.com/%20has%20experienced%20a%20network%20protocol%20violation%20that%20cannot%20be%20repaired.
```

After some digging I discovered that changes to content length cause the issue, looks like changed value is appended to headers keeping the old value as well. 
```
---
Server: Apache
Last-Modified: Sat, 21 Sep 2002 03:22:21 GMT
Accept-Ranges: bytes
Content-Length: 1604
Content-Type: text/html

---
Date: Mon, 18 Nov 2019 19:06:21 GMT
Server: Apache
Last-Modified: Sat, 21 Sep 2002 03:22:21 GMT
Accept-Ranges: bytes
Content-Length: 1604
Content-Type: text/html
Content-Length: 2055
```

The headers are stored in a [MessageClass.](https://docs.python.org/3/library/http.server.html#http.server.BaseHTTPRequestHandler.MessageClass
) Which according to [docs](https://docs.python.org/3/library/email.compat32-message.html#email.message.Message) should be cleared using `__delitem__` to make sure only one key is present.

I have fixed this here: https://github.com/pr11t/selenium-wire/commit/f01f7bf04d3733f9ab9b1f26364e0a10a422360e

**Comment by wkeeling** [comment]
Well found - and many thanks for the fix! PR merged.
