### ISSUE TITLE
import fail

### ISSUE THREAD

**Issue by relesssar** [wkeeling/selenium-wire#83]
I installed with:
pip install selenium-wire
and error import in:
from seleniumwire import webdriver
what am doing wrong?

```
Traceback (most recent call last):
  File "python/examples/instafollower_parse.py", line 4, in <module>
    from seleniumwire import webdriver  # Import from seleniumwire
  File "/usr/local/lib/python2.7/dist-packages/seleniumwire/webdriver/__init__.py", line 3, in <module>
    from .browser import Chrome, Edge, Firefox, Safari  # noqa
  File "/usr/local/lib/python2.7/dist-packages/seleniumwire/webdriver/browser.py", line 14
    def __init__(self, *args, seleniumwire_options=None, **kwargs):
                                                 ^
SyntaxError: invalid syntax
```

**Comment by wkeeling** [comment]
What version of Python are you using?

**Comment by wkeeling** [comment]
What version of Python are you using?

**Comment by relesssar** [comment]
python2.7

**Comment by wkeeling** [comment]
Selenium Wire is [not compatible with Python 2](https://github.com/wkeeling/selenium-wire#compatibilty) I'm afraid. You'll need to upgrade to Python 3.4 or higher.
