### ISSUE TITLE
Headless chrome is slower to start and also throws error

### ISSUE THREAD

**Issue by appunni-dishq** [wkeeling/selenium-wire#9]
Exception happened during processing of request from ('127.0.0.1', 51648)
Traceback (most recent call last):
  File "/usr/lib/python3.5/socketserver.py", line 625, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.5/socketserver.py", line 354, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/home/user/.virtualenvs/project/lib/python3.5/site-packages/seleniumwire/proxy/proxy2.py", line 65, in __init__
    super().__init__(*args, **kwargs)
  File "/usr/lib/python3.5/socketserver.py", line 681, in __init__
    self.handle()
  File "/usr/lib/python3.5/http/server.py", line 422, in handle
    self.handle_one_request()
  File "/usr/lib/python3.5/http/server.py", line 410, in handle_one_request
    method()
  File "/home/user/.virtualenvs/project/lib/python3.5/site-packages/seleniumwire/proxy/proxy2.py", line 76, in do_CONNECT
    self.connect_intercept()
  File "/home/user/.virtualenvs/project/lib/python3.5/site-packages/seleniumwire/proxy/proxy2.py", line 106, in connect_intercept
    with ssl.wrap_socket(self.connection, keyfile=self.certkey, certfile=certpath, server_side=True) as conn:
  File "/usr/lib/python3.5/ssl.py", line 1069, in wrap_socket
    ciphers=ciphers)
  File "/usr/lib/python3.5/ssl.py", line 752, in __init__
    self.do_handshake()
  File "/usr/lib/python3.5/ssl.py", line 988, in do_handshake
    self._sslobj.do_handshake()
  File "/usr/lib/python3.5/ssl.py", line 633, in do_handshake
    self._sslobj.do_handshake()
ConnectionResetError: [Errno 104] Connection reset by peer

This happens in headless browser only

**Comment by wkeeling** [comment]
Hi @appunni-dishq - many thanks for raising this issue. 

When running in headless mode, are you passing any other arguments to the webdriver instance other than `--headless`?

**Comment by appunni-dishq** [comment]
I am using OpenVPN to connect to the internet. When I didn't use any VPN it worked. Also, I need to use HTTP_PROXY and HTTPS_PROXY.

**Comment by appunni-dishq** [comment]
And problem is HTTPS proxy is also using http to communicate

**Comment by appunni-dishq** [comment]
Problem went away when I am not using VPN and I am able to use external proxy

**Comment by appunni-dishq** [comment]
I think I found it out. I opened the page using Chrome Browser without headless with caching, and user-dir. Then I tried to run it using headless with same user-dir. By removing my old user dir solved the issue. But still, the headless browser is very slow to startup.

**Comment by wkeeling** [comment]
@appunni-dishq Many thanks for the extra info.

Regarding the performance, there is a known issue where gzipped content is slow to load, but that would affect both headless and non-headless. Might be worth having a look at #1 just in case.

**Comment by appunni-dishq** [comment]
@wkeeling Thanks for the note, I will check it out.
