### ISSUE TITLE
Selenium wire in docker throw "Permission denied: '/.seleniumwire'"

### ISSUE THREAD

**Issue by Draqun** [wkeeling/selenium-wire#90]
Hi.
I have problem with seleniumwire. When I try run application in docker on the openshift than from application Permission Denied exception is raised. IT does not occurs on the local machine. In docker tests are run with root permissions. Do you know what is wrong? Any help will be appreciated.

Draqun

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.8/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.8/site-packages/xmlrunner/__main__.py", line 19, in <module>
    XMLTestProgram(module=None)
  File "/usr/local/lib/python3.8/site-packages/xmlrunner/runner.py", line 129, in __init__
    super(XMLTestProgram, self).__init__(*args, **kwargs)
  File "/usr/local/lib/python3.8/unittest/main.py", line 100, in __init__
    self.parseArgs(argv)
  File "/usr/local/lib/python3.8/unittest/main.py", line 147, in parseArgs
    self.createTests()
  File "/usr/local/lib/python3.8/unittest/main.py", line 158, in createTests
    self.test = self.testLoader.loadTestsFromNames(self.testNames,
  File "/usr/local/lib/python3.8/unittest/loader.py", line 220, in loadTestsFromNames
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/usr/local/lib/python3.8/unittest/loader.py", line 220, in <listcomp>
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/usr/local/lib/python3.8/unittest/loader.py", line 154, in loadTestsFromName
    module = __import__(module_name)
  File "/test/main_test.py", line 15, in <module>
    from api_test import *
  File "/test/api_test/__init__.py", line 8, in <module>
    from api_test.booking import CBTDS42BookingTest
  File "/test/api_test/booking/__init__.py", line 8, in <module>
    from api_test.booking.cbtds_42_test import CBTDS42BookingTest
  File "/test/api_test/booking/cbtds_42_test.py", line 10, in <module>
    import configuration as c
  File "/test/configuration.py", line 60, in <module>
    token = Token(chrome_options, proxy_var, base_url, run_in_docker, user_email, user_password)
  File "/test/helpers/configuration/token.py", line 55, in __init__
    self.driver = swdriver.Chrome(seleniumwire_options=wire_options, options=options_obj)
  File "/usr/local/lib/python3.8/site-packages/seleniumwire/webdriver/browser.py", line 66, in __init__
    addr, port = self._client.create_proxy(
  File "/usr/local/lib/python3.8/site-packages/seleniumwire/proxy/client.py", line 53, in create_proxy
    self._proxy = ProxyHTTPServer((addr, port), CaptureRequestHandler,
  File "/usr/local/lib/python3.8/site-packages/seleniumwire/proxy/server.py", line 15, in __init__
    self.storage = RequestStorage()
  File "/usr/local/lib/python3.8/site-packages/seleniumwire/proxy/storage.py", line 40, in __init__
    os.makedirs(self._storage_dir)
  File "/usr/local/lib/python3.8/os.py", line 211, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/usr/local/lib/python3.8/os.py", line 221, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/.seleniumwire'
Exception ignored in: <function Token.__del__ at 0x7fa9bff739d0>
Traceback (most recent call last):
  File "/test/helpers/configuration/token.py", line 61, in __del__
    del self.driver
AttributeError: driver

```

**Comment by Draqun** [comment]
Problem solved: in openshift when docker is run than user does not have root UID (and group does not have GID).

To resolve problem there is need setup run user correct UID/GID.

**Comment by wkeeling** [comment]
Glad you solved this in the end, and thanks for posting the solution.

**Comment by geomario** [comment]
Hey, do you have the docker in the docker hub? I am searching for the selenium-wire docker.  😊

**Comment by wkeeling** [comment]
@geomario Unfortunately not at the present time. Getting Selenium Wire onto Docker Hub is perhaps something we should look at though. I'll open a separate issue.

**Comment by geomario** [comment]
Hola, thanks for the answer. That sounds great, I will have a look then in issue #243 and contribute there. Cheers!
